//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Tournament_Stub_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class LobbyEventDTO
    {
        
        // The type of event that was triggered
        [JsonProperty("eventType")]
        private string _eventType;
        
        // The summoner that triggered the event
        [JsonProperty("summonerId")]
        private string _summonerId;
        
        // Timestamp from the event
        [JsonProperty("timestamp")]
        private string _timestamp;
        
        // The type of event that was triggered
        public string EventType
        {
            get
            {
                return this._eventType;
            }
            set
            {
                this._eventType = value;
            }
        }
        
        // The summoner that triggered the event
        public string SummonerId
        {
            get
            {
                return this._summonerId;
            }
            set
            {
                this._summonerId = value;
            }
        }
        
        // Timestamp from the event
        public string Timestamp
        {
            get
            {
                return this._timestamp;
            }
            set
            {
                this._timestamp = value;
            }
        }
    }
}
