//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Match_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    using RiotSharp.Misc.Converters;
    using RiotSharp.Match_V3.Enums.Converters;
    using RiotSharp.Match_V3.Enums;
    
    
    // 
    public class MatchReferenceDto
    {
        
        // 
        [JsonProperty("lane")]
        private string _lane;
        
        // 
        [JsonProperty("gameId")]
        private long _gameId;
        
        // 
        [JsonProperty("champion")]
        private int _champion;
        
        // 
        [JsonProperty("platformId")]
        private string _platformId;
        
        // 
        [JsonProperty("season")]
        [JsonConverter(typeof(SeasonConverter))]
        private Season _season;
        
        // 
        [JsonProperty("queue")]
        private int _queue;
        
        // 
        [JsonProperty("role")]
        private string _role;
        
        // 
        [JsonProperty("timestamp")]
        [JsonConverter(typeof(DateTimeConverterFromLong))]
        private DateTime _timestamp;
        
        // 
        public string Lane
        {
            get
            {
                return this._lane;
            }
            set
            {
                this._lane = value;
            }
        }
        
        // 
        public long GameId
        {
            get
            {
                return this._gameId;
            }
            set
            {
                this._gameId = value;
            }
        }
        
        // 
        public int Champion
        {
            get
            {
                return this._champion;
            }
            set
            {
                this._champion = value;
            }
        }
        
        // 
        public string PlatformId
        {
            get
            {
                return this._platformId;
            }
            set
            {
                this._platformId = value;
            }
        }
        
        // 
        public Season Season
        {
            get
            {
                return this._season;
            }
            set
            {
                this._season = value;
            }
        }
        
        // 
        public int Queue
        {
            get
            {
                return this._queue;
            }
            set
            {
                this._queue = value;
            }
        }
        
        // 
        public string Role
        {
            get
            {
                return this._role;
            }
            set
            {
                this._role = value;
            }
        }
        
        // 
        public DateTime Timestamp
        {
            get
            {
                return this._timestamp;
            }
            set
            {
                this._timestamp = value;
            }
        }
    }
}
