//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Match_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class MatchParticipantFrameDto
    {
        
        // 
        [JsonProperty("totalGold")]
        private int _totalGold;
        
        // 
        [JsonProperty("teamScore")]
        private int _teamScore;
        
        // 
        [JsonProperty("participantId")]
        private int _participantId;
        
        // 
        [JsonProperty("level")]
        private int _level;
        
        // 
        [JsonProperty("currentGold")]
        private int _currentGold;
        
        // 
        [JsonProperty("minionsKilled")]
        private int _minionsKilled;
        
        // 
        [JsonProperty("dominionScore")]
        private int _dominionScore;
        
        // 
        [JsonProperty("position")]
        private MatchPositionDto _position;
        
        // 
        [JsonProperty("xp")]
        private int _xp;
        
        // 
        [JsonProperty("jungleMinionsKilled")]
        private int _jungleMinionsKilled;
        
        // 
        public int TotalGold
        {
            get
            {
                return this._totalGold;
            }
            set
            {
                this._totalGold = value;
            }
        }
        
        // 
        public int TeamScore
        {
            get
            {
                return this._teamScore;
            }
            set
            {
                this._teamScore = value;
            }
        }
        
        // 
        public int ParticipantId
        {
            get
            {
                return this._participantId;
            }
            set
            {
                this._participantId = value;
            }
        }
        
        // 
        public int Level
        {
            get
            {
                return this._level;
            }
            set
            {
                this._level = value;
            }
        }
        
        // 
        public int CurrentGold
        {
            get
            {
                return this._currentGold;
            }
            set
            {
                this._currentGold = value;
            }
        }
        
        // 
        public int MinionsKilled
        {
            get
            {
                return this._minionsKilled;
            }
            set
            {
                this._minionsKilled = value;
            }
        }
        
        // 
        public int DominionScore
        {
            get
            {
                return this._dominionScore;
            }
            set
            {
                this._dominionScore = value;
            }
        }
        
        // 
        public MatchPositionDto Position
        {
            get
            {
                return this._position;
            }
            set
            {
                this._position = value;
            }
        }
        
        // 
        public int Xp
        {
            get
            {
                return this._xp;
            }
            set
            {
                this._xp = value;
            }
        }
        
        // 
        public int JungleMinionsKilled
        {
            get
            {
                return this._jungleMinionsKilled;
            }
            set
            {
                this._jungleMinionsKilled = value;
            }
        }
    }
}
