//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Match_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class MatchFrameDto
    {
        
        // 
        [JsonProperty("timestamp")]
        private long _timestamp;
        
        // 
        [JsonProperty("participantFrames")]
        private System.Collections.Generic.Dictionary<int, MatchParticipantFrameDto> _participantFrames;
        
        // 
        [JsonProperty("events")]
        private List<MatchEventDto> _events;
        
        // 
        public long Timestamp
        {
            get
            {
                return this._timestamp;
            }
            set
            {
                this._timestamp = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<int, MatchParticipantFrameDto> ParticipantFrames
        {
            get
            {
                return this._participantFrames;
            }
            set
            {
                this._participantFrames = value;
            }
        }
        
        // 
        public List<MatchEventDto> Events
        {
            get
            {
                return this._events;
            }
            set
            {
                this._events = value;
            }
        }
    }
}
