//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Match_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class ParticipantStatsDto
    {
        
        // 
        [JsonProperty("physicalDamageDealt")]
        private long _physicalDamageDealt;
        
        // 
        [JsonProperty("neutralMinionsKilledTeamJungle")]
        private int _neutralMinionsKilledTeamJungle;
        
        // 
        [JsonProperty("magicDamageDealt")]
        private long _magicDamageDealt;
        
        // 
        [JsonProperty("totalPlayerScore")]
        private int _totalPlayerScore;
        
        // 
        [JsonProperty("deaths")]
        private int _deaths;
        
        // 
        [JsonProperty("win")]
        private bool _win;
        
        // 
        [JsonProperty("neutralMinionsKilledEnemyJungle")]
        private int _neutralMinionsKilledEnemyJungle;
        
        // 
        [JsonProperty("altarsCaptured")]
        private int _altarsCaptured;
        
        // 
        [JsonProperty("largestCriticalStrike")]
        private int _largestCriticalStrike;
        
        // 
        [JsonProperty("totalDamageDealt")]
        private long _totalDamageDealt;
        
        // 
        [JsonProperty("magicDamageDealtToChampions")]
        private long _magicDamageDealtToChampions;
        
        // 
        [JsonProperty("visionWardsBoughtInGame")]
        private int _visionWardsBoughtInGame;
        
        // 
        [JsonProperty("damageDealtToObjectives")]
        private long _damageDealtToObjectives;
        
        // 
        [JsonProperty("largestKillingSpree")]
        private int _largestKillingSpree;
        
        // 
        [JsonProperty("item1")]
        private int _item1;
        
        // 
        [JsonProperty("quadraKills")]
        private int _quadraKills;
        
        // 
        [JsonProperty("teamObjective")]
        private int _teamObjective;
        
        // 
        [JsonProperty("totalTimeCrowdControlDealt")]
        private int _totalTimeCrowdControlDealt;
        
        // 
        [JsonProperty("longestTimeSpentLiving")]
        private int _longestTimeSpentLiving;
        
        // 
        [JsonProperty("wardsKilled")]
        private int _wardsKilled;
        
        // 
        [JsonProperty("firstTowerAssist")]
        private bool _firstTowerAssist;
        
        // 
        [JsonProperty("firstTowerKill")]
        private bool _firstTowerKill;
        
        // 
        [JsonProperty("item2")]
        private int _item2;
        
        // 
        [JsonProperty("item3")]
        private int _item3;
        
        // 
        [JsonProperty("item0")]
        private int _item0;
        
        // 
        [JsonProperty("firstBloodAssist")]
        private bool _firstBloodAssist;
        
        // 
        [JsonProperty("visionScore")]
        private long _visionScore;
        
        // 
        [JsonProperty("wardsPlaced")]
        private int _wardsPlaced;
        
        // 
        [JsonProperty("item4")]
        private int _item4;
        
        // 
        [JsonProperty("item5")]
        private int _item5;
        
        // 
        [JsonProperty("item6")]
        private int _item6;
        
        // 
        [JsonProperty("turretKills")]
        private int _turretKills;
        
        // 
        [JsonProperty("tripleKills")]
        private int _tripleKills;
        
        // 
        [JsonProperty("damageSelfMitigated")]
        private long _damageSelfMitigated;
        
        // 
        [JsonProperty("champLevel")]
        private int _champLevel;
        
        // 
        [JsonProperty("nodeNeutralizeAssist")]
        private int _nodeNeutralizeAssist;
        
        // 
        [JsonProperty("firstInhibitorKill")]
        private bool _firstInhibitorKill;
        
        // 
        [JsonProperty("goldEarned")]
        private int _goldEarned;
        
        // 
        [JsonProperty("magicalDamageTaken")]
        private long _magicalDamageTaken;
        
        // 
        [JsonProperty("kills")]
        private int _kills;
        
        // 
        [JsonProperty("doubleKills")]
        private int _doubleKills;
        
        // 
        [JsonProperty("nodeCaptureAssist")]
        private int _nodeCaptureAssist;
        
        // 
        [JsonProperty("trueDamageTaken")]
        private long _trueDamageTaken;
        
        // 
        [JsonProperty("nodeNeutralize")]
        private int _nodeNeutralize;
        
        // 
        [JsonProperty("firstInhibitorAssist")]
        private bool _firstInhibitorAssist;
        
        // 
        [JsonProperty("assists")]
        private int _assists;
        
        // 
        [JsonProperty("unrealKills")]
        private int _unrealKills;
        
        // 
        [JsonProperty("neutralMinionsKilled")]
        private int _neutralMinionsKilled;
        
        // 
        [JsonProperty("objectivePlayerScore")]
        private int _objectivePlayerScore;
        
        // 
        [JsonProperty("combatPlayerScore")]
        private int _combatPlayerScore;
        
        // 
        [JsonProperty("damageDealtToTurrets")]
        private long _damageDealtToTurrets;
        
        // 
        [JsonProperty("altarsNeutralized")]
        private int _altarsNeutralized;
        
        // 
        [JsonProperty("physicalDamageDealtToChampions")]
        private long _physicalDamageDealtToChampions;
        
        // 
        [JsonProperty("goldSpent")]
        private int _goldSpent;
        
        // 
        [JsonProperty("trueDamageDealt")]
        private long _trueDamageDealt;
        
        // 
        [JsonProperty("trueDamageDealtToChampions")]
        private long _trueDamageDealtToChampions;
        
        // 
        [JsonProperty("participantId")]
        private int _participantId;
        
        // 
        [JsonProperty("pentaKills")]
        private int _pentaKills;
        
        // 
        [JsonProperty("totalHeal")]
        private long _totalHeal;
        
        // 
        [JsonProperty("totalMinionsKilled")]
        private int _totalMinionsKilled;
        
        // 
        [JsonProperty("firstBloodKill")]
        private bool _firstBloodKill;
        
        // 
        [JsonProperty("nodeCapture")]
        private int _nodeCapture;
        
        // 
        [JsonProperty("largestMultiKill")]
        private int _largestMultiKill;
        
        // 
        [JsonProperty("sightWardsBoughtInGame")]
        private int _sightWardsBoughtInGame;
        
        // 
        [JsonProperty("totalDamageDealtToChampions")]
        private long _totalDamageDealtToChampions;
        
        // 
        [JsonProperty("totalUnitsHealed")]
        private int _totalUnitsHealed;
        
        // 
        [JsonProperty("inhibitorKills")]
        private int _inhibitorKills;
        
        // 
        [JsonProperty("totalScoreRank")]
        private int _totalScoreRank;
        
        // 
        [JsonProperty("totalDamageTaken")]
        private long _totalDamageTaken;
        
        // 
        [JsonProperty("killingSprees")]
        private int _killingSprees;
        
        // 
        [JsonProperty("timeCCingOthers")]
        private long _timeCCingOthers;
        
        // 
        [JsonProperty("physicalDamageTaken")]
        private long _physicalDamageTaken;
        
        // 
        public long PhysicalDamageDealt
        {
            get
            {
                return this._physicalDamageDealt;
            }
            set
            {
                this._physicalDamageDealt = value;
            }
        }
        
        // 
        public int NeutralMinionsKilledTeamJungle
        {
            get
            {
                return this._neutralMinionsKilledTeamJungle;
            }
            set
            {
                this._neutralMinionsKilledTeamJungle = value;
            }
        }
        
        // 
        public long MagicDamageDealt
        {
            get
            {
                return this._magicDamageDealt;
            }
            set
            {
                this._magicDamageDealt = value;
            }
        }
        
        // 
        public int TotalPlayerScore
        {
            get
            {
                return this._totalPlayerScore;
            }
            set
            {
                this._totalPlayerScore = value;
            }
        }
        
        // 
        public int Deaths
        {
            get
            {
                return this._deaths;
            }
            set
            {
                this._deaths = value;
            }
        }
        
        // 
        public bool Win
        {
            get
            {
                return this._win;
            }
            set
            {
                this._win = value;
            }
        }
        
        // 
        public int NeutralMinionsKilledEnemyJungle
        {
            get
            {
                return this._neutralMinionsKilledEnemyJungle;
            }
            set
            {
                this._neutralMinionsKilledEnemyJungle = value;
            }
        }
        
        // 
        public int AltarsCaptured
        {
            get
            {
                return this._altarsCaptured;
            }
            set
            {
                this._altarsCaptured = value;
            }
        }
        
        // 
        public int LargestCriticalStrike
        {
            get
            {
                return this._largestCriticalStrike;
            }
            set
            {
                this._largestCriticalStrike = value;
            }
        }
        
        // 
        public long TotalDamageDealt
        {
            get
            {
                return this._totalDamageDealt;
            }
            set
            {
                this._totalDamageDealt = value;
            }
        }
        
        // 
        public long MagicDamageDealtToChampions
        {
            get
            {
                return this._magicDamageDealtToChampions;
            }
            set
            {
                this._magicDamageDealtToChampions = value;
            }
        }
        
        // 
        public int VisionWardsBoughtInGame
        {
            get
            {
                return this._visionWardsBoughtInGame;
            }
            set
            {
                this._visionWardsBoughtInGame = value;
            }
        }
        
        // 
        public long DamageDealtToObjectives
        {
            get
            {
                return this._damageDealtToObjectives;
            }
            set
            {
                this._damageDealtToObjectives = value;
            }
        }
        
        // 
        public int LargestKillingSpree
        {
            get
            {
                return this._largestKillingSpree;
            }
            set
            {
                this._largestKillingSpree = value;
            }
        }
        
        // 
        public int Item1
        {
            get
            {
                return this._item1;
            }
            set
            {
                this._item1 = value;
            }
        }
        
        // 
        public int QuadraKills
        {
            get
            {
                return this._quadraKills;
            }
            set
            {
                this._quadraKills = value;
            }
        }
        
        // 
        public int TeamObjective
        {
            get
            {
                return this._teamObjective;
            }
            set
            {
                this._teamObjective = value;
            }
        }
        
        // 
        public int TotalTimeCrowdControlDealt
        {
            get
            {
                return this._totalTimeCrowdControlDealt;
            }
            set
            {
                this._totalTimeCrowdControlDealt = value;
            }
        }
        
        // 
        public int LongestTimeSpentLiving
        {
            get
            {
                return this._longestTimeSpentLiving;
            }
            set
            {
                this._longestTimeSpentLiving = value;
            }
        }
        
        // 
        public int WardsKilled
        {
            get
            {
                return this._wardsKilled;
            }
            set
            {
                this._wardsKilled = value;
            }
        }
        
        // 
        public bool FirstTowerAssist
        {
            get
            {
                return this._firstTowerAssist;
            }
            set
            {
                this._firstTowerAssist = value;
            }
        }
        
        // 
        public bool FirstTowerKill
        {
            get
            {
                return this._firstTowerKill;
            }
            set
            {
                this._firstTowerKill = value;
            }
        }
        
        // 
        public int Item2
        {
            get
            {
                return this._item2;
            }
            set
            {
                this._item2 = value;
            }
        }
        
        // 
        public int Item3
        {
            get
            {
                return this._item3;
            }
            set
            {
                this._item3 = value;
            }
        }
        
        // 
        public int Item0
        {
            get
            {
                return this._item0;
            }
            set
            {
                this._item0 = value;
            }
        }
        
        // 
        public bool FirstBloodAssist
        {
            get
            {
                return this._firstBloodAssist;
            }
            set
            {
                this._firstBloodAssist = value;
            }
        }
        
        // 
        public long VisionScore
        {
            get
            {
                return this._visionScore;
            }
            set
            {
                this._visionScore = value;
            }
        }
        
        // 
        public int WardsPlaced
        {
            get
            {
                return this._wardsPlaced;
            }
            set
            {
                this._wardsPlaced = value;
            }
        }
        
        // 
        public int Item4
        {
            get
            {
                return this._item4;
            }
            set
            {
                this._item4 = value;
            }
        }
        
        // 
        public int Item5
        {
            get
            {
                return this._item5;
            }
            set
            {
                this._item5 = value;
            }
        }
        
        // 
        public int Item6
        {
            get
            {
                return this._item6;
            }
            set
            {
                this._item6 = value;
            }
        }
        
        // 
        public int TurretKills
        {
            get
            {
                return this._turretKills;
            }
            set
            {
                this._turretKills = value;
            }
        }
        
        // 
        public int TripleKills
        {
            get
            {
                return this._tripleKills;
            }
            set
            {
                this._tripleKills = value;
            }
        }
        
        // 
        public long DamageSelfMitigated
        {
            get
            {
                return this._damageSelfMitigated;
            }
            set
            {
                this._damageSelfMitigated = value;
            }
        }
        
        // 
        public int ChampLevel
        {
            get
            {
                return this._champLevel;
            }
            set
            {
                this._champLevel = value;
            }
        }
        
        // 
        public int NodeNeutralizeAssist
        {
            get
            {
                return this._nodeNeutralizeAssist;
            }
            set
            {
                this._nodeNeutralizeAssist = value;
            }
        }
        
        // 
        public bool FirstInhibitorKill
        {
            get
            {
                return this._firstInhibitorKill;
            }
            set
            {
                this._firstInhibitorKill = value;
            }
        }
        
        // 
        public int GoldEarned
        {
            get
            {
                return this._goldEarned;
            }
            set
            {
                this._goldEarned = value;
            }
        }
        
        // 
        public long MagicalDamageTaken
        {
            get
            {
                return this._magicalDamageTaken;
            }
            set
            {
                this._magicalDamageTaken = value;
            }
        }
        
        // 
        public int Kills
        {
            get
            {
                return this._kills;
            }
            set
            {
                this._kills = value;
            }
        }
        
        // 
        public int DoubleKills
        {
            get
            {
                return this._doubleKills;
            }
            set
            {
                this._doubleKills = value;
            }
        }
        
        // 
        public int NodeCaptureAssist
        {
            get
            {
                return this._nodeCaptureAssist;
            }
            set
            {
                this._nodeCaptureAssist = value;
            }
        }
        
        // 
        public long TrueDamageTaken
        {
            get
            {
                return this._trueDamageTaken;
            }
            set
            {
                this._trueDamageTaken = value;
            }
        }
        
        // 
        public int NodeNeutralize
        {
            get
            {
                return this._nodeNeutralize;
            }
            set
            {
                this._nodeNeutralize = value;
            }
        }
        
        // 
        public bool FirstInhibitorAssist
        {
            get
            {
                return this._firstInhibitorAssist;
            }
            set
            {
                this._firstInhibitorAssist = value;
            }
        }
        
        // 
        public int Assists
        {
            get
            {
                return this._assists;
            }
            set
            {
                this._assists = value;
            }
        }
        
        // 
        public int UnrealKills
        {
            get
            {
                return this._unrealKills;
            }
            set
            {
                this._unrealKills = value;
            }
        }
        
        // 
        public int NeutralMinionsKilled
        {
            get
            {
                return this._neutralMinionsKilled;
            }
            set
            {
                this._neutralMinionsKilled = value;
            }
        }
        
        // 
        public int ObjectivePlayerScore
        {
            get
            {
                return this._objectivePlayerScore;
            }
            set
            {
                this._objectivePlayerScore = value;
            }
        }
        
        // 
        public int CombatPlayerScore
        {
            get
            {
                return this._combatPlayerScore;
            }
            set
            {
                this._combatPlayerScore = value;
            }
        }
        
        // 
        public long DamageDealtToTurrets
        {
            get
            {
                return this._damageDealtToTurrets;
            }
            set
            {
                this._damageDealtToTurrets = value;
            }
        }
        
        // 
        public int AltarsNeutralized
        {
            get
            {
                return this._altarsNeutralized;
            }
            set
            {
                this._altarsNeutralized = value;
            }
        }
        
        // 
        public long PhysicalDamageDealtToChampions
        {
            get
            {
                return this._physicalDamageDealtToChampions;
            }
            set
            {
                this._physicalDamageDealtToChampions = value;
            }
        }
        
        // 
        public int GoldSpent
        {
            get
            {
                return this._goldSpent;
            }
            set
            {
                this._goldSpent = value;
            }
        }
        
        // 
        public long TrueDamageDealt
        {
            get
            {
                return this._trueDamageDealt;
            }
            set
            {
                this._trueDamageDealt = value;
            }
        }
        
        // 
        public long TrueDamageDealtToChampions
        {
            get
            {
                return this._trueDamageDealtToChampions;
            }
            set
            {
                this._trueDamageDealtToChampions = value;
            }
        }
        
        // 
        public int ParticipantId
        {
            get
            {
                return this._participantId;
            }
            set
            {
                this._participantId = value;
            }
        }
        
        // 
        public int PentaKills
        {
            get
            {
                return this._pentaKills;
            }
            set
            {
                this._pentaKills = value;
            }
        }
        
        // 
        public long TotalHeal
        {
            get
            {
                return this._totalHeal;
            }
            set
            {
                this._totalHeal = value;
            }
        }
        
        // 
        public int TotalMinionsKilled
        {
            get
            {
                return this._totalMinionsKilled;
            }
            set
            {
                this._totalMinionsKilled = value;
            }
        }
        
        // 
        public bool FirstBloodKill
        {
            get
            {
                return this._firstBloodKill;
            }
            set
            {
                this._firstBloodKill = value;
            }
        }
        
        // 
        public int NodeCapture
        {
            get
            {
                return this._nodeCapture;
            }
            set
            {
                this._nodeCapture = value;
            }
        }
        
        // 
        public int LargestMultiKill
        {
            get
            {
                return this._largestMultiKill;
            }
            set
            {
                this._largestMultiKill = value;
            }
        }
        
        // 
        public int SightWardsBoughtInGame
        {
            get
            {
                return this._sightWardsBoughtInGame;
            }
            set
            {
                this._sightWardsBoughtInGame = value;
            }
        }
        
        // 
        public long TotalDamageDealtToChampions
        {
            get
            {
                return this._totalDamageDealtToChampions;
            }
            set
            {
                this._totalDamageDealtToChampions = value;
            }
        }
        
        // 
        public int TotalUnitsHealed
        {
            get
            {
                return this._totalUnitsHealed;
            }
            set
            {
                this._totalUnitsHealed = value;
            }
        }
        
        // 
        public int InhibitorKills
        {
            get
            {
                return this._inhibitorKills;
            }
            set
            {
                this._inhibitorKills = value;
            }
        }
        
        // 
        public int TotalScoreRank
        {
            get
            {
                return this._totalScoreRank;
            }
            set
            {
                this._totalScoreRank = value;
            }
        }
        
        // 
        public long TotalDamageTaken
        {
            get
            {
                return this._totalDamageTaken;
            }
            set
            {
                this._totalDamageTaken = value;
            }
        }
        
        // 
        public int KillingSprees
        {
            get
            {
                return this._killingSprees;
            }
            set
            {
                this._killingSprees = value;
            }
        }
        
        // 
        public long TimeCCingOthers
        {
            get
            {
                return this._timeCCingOthers;
            }
            set
            {
                this._timeCCingOthers = value;
            }
        }
        
        // 
        public long PhysicalDamageTaken
        {
            get
            {
                return this._physicalDamageTaken;
            }
            set
            {
                this._physicalDamageTaken = value;
            }
        }
    }
}
