//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Match_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class ParticipantTimelineDto
    {
        
        // 
        [JsonProperty("lane")]
        private string _lane;
        
        // 
        [JsonProperty("participantId")]
        private int _participantId;
        
        // 
        [JsonProperty("csDiffPerMinDeltas")]
        private System.Collections.Generic.Dictionary<string, double> _csDiffPerMinDeltas;
        
        // 
        [JsonProperty("goldPerMinDeltas")]
        private System.Collections.Generic.Dictionary<string, double> _goldPerMinDeltas;
        
        // 
        [JsonProperty("xpDiffPerMinDeltas")]
        private System.Collections.Generic.Dictionary<string, double> _xpDiffPerMinDeltas;
        
        // 
        [JsonProperty("creepsPerMinDeltas")]
        private System.Collections.Generic.Dictionary<string, double> _creepsPerMinDeltas;
        
        // 
        [JsonProperty("xpPerMinDeltas")]
        private System.Collections.Generic.Dictionary<string, double> _xpPerMinDeltas;
        
        // 
        [JsonProperty("role")]
        private string _role;
        
        // 
        [JsonProperty("damageTakenDiffPerMinDeltas")]
        private System.Collections.Generic.Dictionary<string, double> _damageTakenDiffPerMinDeltas;
        
        // 
        [JsonProperty("damageTakenPerMinDeltas")]
        private System.Collections.Generic.Dictionary<string, double> _damageTakenPerMinDeltas;
        
        // 
        public string Lane
        {
            get
            {
                return this._lane;
            }
            set
            {
                this._lane = value;
            }
        }
        
        // 
        public int ParticipantId
        {
            get
            {
                return this._participantId;
            }
            set
            {
                this._participantId = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<string, double> CsDiffPerMinDeltas
        {
            get
            {
                return this._csDiffPerMinDeltas;
            }
            set
            {
                this._csDiffPerMinDeltas = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<string, double> GoldPerMinDeltas
        {
            get
            {
                return this._goldPerMinDeltas;
            }
            set
            {
                this._goldPerMinDeltas = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<string, double> XpDiffPerMinDeltas
        {
            get
            {
                return this._xpDiffPerMinDeltas;
            }
            set
            {
                this._xpDiffPerMinDeltas = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<string, double> CreepsPerMinDeltas
        {
            get
            {
                return this._creepsPerMinDeltas;
            }
            set
            {
                this._creepsPerMinDeltas = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<string, double> XpPerMinDeltas
        {
            get
            {
                return this._xpPerMinDeltas;
            }
            set
            {
                this._xpPerMinDeltas = value;
            }
        }
        
        // 
        public string Role
        {
            get
            {
                return this._role;
            }
            set
            {
                this._role = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<string, double> DamageTakenDiffPerMinDeltas
        {
            get
            {
                return this._damageTakenDiffPerMinDeltas;
            }
            set
            {
                this._damageTakenDiffPerMinDeltas = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<string, double> DamageTakenPerMinDeltas
        {
            get
            {
                return this._damageTakenPerMinDeltas;
            }
            set
            {
                this._damageTakenPerMinDeltas = value;
            }
        }
    }
}
