//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Match_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class ParticipantIdentityDto
    {
        
        // 
        [JsonProperty("player")]
        private PlayerDto _player;
        
        // 
        [JsonProperty("participantId")]
        private int _participantId;
        
        // 
        public PlayerDto Player
        {
            get
            {
                return this._player;
            }
            set
            {
                this._player = value;
            }
        }
        
        // 
        public int ParticipantId
        {
            get
            {
                return this._participantId;
            }
            set
            {
                this._participantId = value;
            }
        }
    }
}
