//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Match_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class PlayerDto
    {
        
        // 
        [JsonProperty("currentPlatformId")]
        private string _currentPlatformId;
        
        // 
        [JsonProperty("summonerName")]
        private string _summonerName;
        
        // 
        [JsonProperty("matchHistoryUri")]
        private string _matchHistoryUri;
        
        // 
        [JsonProperty("platformId")]
        private string _platformId;
        
        // 
        [JsonProperty("currentAccountId")]
        private long _currentAccountId;
        
        // 
        [JsonProperty("profileIcon")]
        private int _profileIcon;
        
        // 
        [JsonProperty("summonerId")]
        private long _summonerId;
        
        // 
        [JsonProperty("accountId")]
        private long _accountId;
        
        // 
        public string CurrentPlatformId
        {
            get
            {
                return this._currentPlatformId;
            }
            set
            {
                this._currentPlatformId = value;
            }
        }
        
        // 
        public string SummonerName
        {
            get
            {
                return this._summonerName;
            }
            set
            {
                this._summonerName = value;
            }
        }
        
        // 
        public string MatchHistoryUri
        {
            get
            {
                return this._matchHistoryUri;
            }
            set
            {
                this._matchHistoryUri = value;
            }
        }
        
        // 
        public string PlatformId
        {
            get
            {
                return this._platformId;
            }
            set
            {
                this._platformId = value;
            }
        }
        
        // 
        public long CurrentAccountId
        {
            get
            {
                return this._currentAccountId;
            }
            set
            {
                this._currentAccountId = value;
            }
        }
        
        // 
        public int ProfileIcon
        {
            get
            {
                return this._profileIcon;
            }
            set
            {
                this._profileIcon = value;
            }
        }
        
        // 
        public long SummonerId
        {
            get
            {
                return this._summonerId;
            }
            set
            {
                this._summonerId = value;
            }
        }
        
        // 
        public long AccountId
        {
            get
            {
                return this._accountId;
            }
            set
            {
                this._accountId = value;
            }
        }
    }
}
