//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Match_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class TeamStatsDto
    {
        
        // 
        [JsonProperty("firstDragon")]
        private bool _firstDragon;
        
        // 
        [JsonProperty("firstInhibitor")]
        private bool _firstInhibitor;
        
        // 
        [JsonProperty("bans")]
        private List<TeamBansDto> _bans;
        
        // 
        [JsonProperty("baronKills")]
        private int _baronKills;
        
        // 
        [JsonProperty("firstRiftHerald")]
        private bool _firstRiftHerald;
        
        // 
        [JsonProperty("firstBaron")]
        private bool _firstBaron;
        
        // 
        [JsonProperty("riftHeraldKills")]
        private int _riftHeraldKills;
        
        // 
        [JsonProperty("firstBlood")]
        private bool _firstBlood;
        
        // 
        [JsonProperty("teamId")]
        private int _teamId;
        
        // 
        [JsonProperty("firstTower")]
        private bool _firstTower;
        
        // 
        [JsonProperty("vilemawKills")]
        private int _vilemawKills;
        
        // 
        [JsonProperty("inhibitorKills")]
        private int _inhibitorKills;
        
        // 
        [JsonProperty("towerKills")]
        private int _towerKills;
        
        // 
        [JsonProperty("dominionVictoryScore")]
        private int _dominionVictoryScore;
        
        // 
        [JsonProperty("win")]
        private string _win;
        
        // 
        [JsonProperty("dragonKills")]
        private int _dragonKills;
        
        // 
        public bool FirstDragon
        {
            get
            {
                return this._firstDragon;
            }
            set
            {
                this._firstDragon = value;
            }
        }
        
        // 
        public bool FirstInhibitor
        {
            get
            {
                return this._firstInhibitor;
            }
            set
            {
                this._firstInhibitor = value;
            }
        }
        
        // 
        public List<TeamBansDto> Bans
        {
            get
            {
                return this._bans;
            }
            set
            {
                this._bans = value;
            }
        }
        
        // 
        public int BaronKills
        {
            get
            {
                return this._baronKills;
            }
            set
            {
                this._baronKills = value;
            }
        }
        
        // 
        public bool FirstRiftHerald
        {
            get
            {
                return this._firstRiftHerald;
            }
            set
            {
                this._firstRiftHerald = value;
            }
        }
        
        // 
        public bool FirstBaron
        {
            get
            {
                return this._firstBaron;
            }
            set
            {
                this._firstBaron = value;
            }
        }
        
        // 
        public int RiftHeraldKills
        {
            get
            {
                return this._riftHeraldKills;
            }
            set
            {
                this._riftHeraldKills = value;
            }
        }
        
        // 
        public bool FirstBlood
        {
            get
            {
                return this._firstBlood;
            }
            set
            {
                this._firstBlood = value;
            }
        }
        
        // 
        public int TeamId
        {
            get
            {
                return this._teamId;
            }
            set
            {
                this._teamId = value;
            }
        }
        
        // 
        public bool FirstTower
        {
            get
            {
                return this._firstTower;
            }
            set
            {
                this._firstTower = value;
            }
        }
        
        // 
        public int VilemawKills
        {
            get
            {
                return this._vilemawKills;
            }
            set
            {
                this._vilemawKills = value;
            }
        }
        
        // 
        public int InhibitorKills
        {
            get
            {
                return this._inhibitorKills;
            }
            set
            {
                this._inhibitorKills = value;
            }
        }
        
        // 
        public int TowerKills
        {
            get
            {
                return this._towerKills;
            }
            set
            {
                this._towerKills = value;
            }
        }
        
        // 
        public int DominionVictoryScore
        {
            get
            {
                return this._dominionVictoryScore;
            }
            set
            {
                this._dominionVictoryScore = value;
            }
        }
        
        // 
        public string Win
        {
            get
            {
                return this._win;
            }
            set
            {
                this._win = value;
            }
        }
        
        // 
        public int DragonKills
        {
            get
            {
                return this._dragonKills;
            }
            set
            {
                this._dragonKills = value;
            }
        }
    }
}
