//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Match_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class TeamBansDto
    {
        
        // 
        [JsonProperty("pickTurn")]
        private int _pickTurn;
        
        // 
        [JsonProperty("championId")]
        private int _championId;
        
        // 
        public int PickTurn
        {
            get
            {
                return this._pickTurn;
            }
            set
            {
                this._pickTurn = value;
            }
        }
        
        // 
        public int ChampionId
        {
            get
            {
                return this._championId;
            }
            set
            {
                this._championId = value;
            }
        }
    }
}
