//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains champion recommended block data.
    public class BlockDtoStatic
    {
        
        // 
        [JsonProperty("items")]
        private List<BlockItemDtoStatic> _items;
        
        // 
        [JsonProperty("recMath")]
        private bool _recMath;
        
        // 
        [JsonProperty("type")]
        private string _type;
        
        // 
        public List<BlockItemDtoStatic> Items
        {
            get
            {
                return this._items;
            }
            set
            {
                this._items = value;
            }
        }
        
        // 
        public bool RecMath
        {
            get
            {
                return this._recMath;
            }
            set
            {
                this._recMath = value;
            }
        }
        
        // 
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
    }
}
