//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains champion list data.
    public class ChampionListDtoStatic
    {
        
        // 
        [JsonProperty("keys")]
        private System.Collections.Generic.Dictionary<string, string> _keys;
        
        // 
        [JsonProperty("data")]
        private System.Collections.Generic.Dictionary<string, ChampionDtoStatic> _data;
        
        // 
        [JsonProperty("version")]
        private string _version;
        
        // 
        [JsonProperty("type")]
        private string _type;
        
        // 
        [JsonProperty("format")]
        private string _format;
        
        // 
        public System.Collections.Generic.Dictionary<string, string> Keys
        {
            get
            {
                return this._keys;
            }
            set
            {
                this._keys = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<string, ChampionDtoStatic> Data
        {
            get
            {
                return this._data;
            }
            set
            {
                this._data = value;
            }
        }
        
        // 
        public string Version
        {
            get
            {
                return this._version;
            }
            set
            {
                this._version = value;
            }
        }
        
        // 
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        // 
        public string Format
        {
            get
            {
                return this._format;
            }
            set
            {
                this._format = value;
            }
        }
    }
}
