//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains champion spell data.
    public class ChampionSpellDtoStatic
    {
        
        // 
        [JsonProperty("cooldownBurn")]
        private string _cooldownBurn;
        
        // 
        [JsonProperty("resource")]
        private string _resource;
        
        // 
        [JsonProperty("leveltip")]
        private LevelTipDtoStatic _leveltip;
        
        // 
        [JsonProperty("vars")]
        private List<SpellVarsDtoStatic> _vars;
        
        // 
        [JsonProperty("costType")]
        private string _costType;
        
        // 
        [JsonProperty("image")]
        private ImageDtoStatic _image;
        
        // 
        [JsonProperty("sanitizedDescription")]
        private string _sanitizedDescription;
        
        // 
        [JsonProperty("sanitizedTooltip")]
        private string _sanitizedTooltip;
        
        // This field is a List of List of Double.
        [JsonProperty("effect")]
        private List<object> _effect;
        
        // 
        [JsonProperty("tooltip")]
        private string _tooltip;
        
        // 
        [JsonProperty("maxrank")]
        private int _maxrank;
        
        // 
        [JsonProperty("costBurn")]
        private string _costBurn;
        
        // 
        [JsonProperty("rangeBurn")]
        private string _rangeBurn;
        
        // This field is either a List of Integer or the String 'self' for spells that target one's own champion.
        [JsonProperty("range")]
        private object _range;
        
        // 
        [JsonProperty("cooldown")]
        private List<double> _cooldown;
        
        // 
        [JsonProperty("cost")]
        private List<int> _cost;
        
        // 
        [JsonProperty("key")]
        private string _key;
        
        // 
        [JsonProperty("description")]
        private string _description;
        
        // 
        [JsonProperty("effectBurn")]
        private List<string> _effectBurn;
        
        // 
        [JsonProperty("altimages")]
        private List<ImageDtoStatic> _altimages;
        
        // 
        [JsonProperty("name")]
        private string _name;
        
        // 
        public string CooldownBurn
        {
            get
            {
                return this._cooldownBurn;
            }
            set
            {
                this._cooldownBurn = value;
            }
        }
        
        // 
        public string Resource
        {
            get
            {
                return this._resource;
            }
            set
            {
                this._resource = value;
            }
        }
        
        // 
        public LevelTipDtoStatic Leveltip
        {
            get
            {
                return this._leveltip;
            }
            set
            {
                this._leveltip = value;
            }
        }
        
        // 
        public List<SpellVarsDtoStatic> Vars
        {
            get
            {
                return this._vars;
            }
            set
            {
                this._vars = value;
            }
        }
        
        // 
        public string CostType
        {
            get
            {
                return this._costType;
            }
            set
            {
                this._costType = value;
            }
        }
        
        // 
        public ImageDtoStatic Image
        {
            get
            {
                return this._image;
            }
            set
            {
                this._image = value;
            }
        }
        
        // 
        public string SanitizedDescription
        {
            get
            {
                return this._sanitizedDescription;
            }
            set
            {
                this._sanitizedDescription = value;
            }
        }
        
        // 
        public string SanitizedTooltip
        {
            get
            {
                return this._sanitizedTooltip;
            }
            set
            {
                this._sanitizedTooltip = value;
            }
        }
        
        // This field is a List of List of Double.
        public List<object> Effect
        {
            get
            {
                return this._effect;
            }
            set
            {
                this._effect = value;
            }
        }
        
        // 
        public string Tooltip
        {
            get
            {
                return this._tooltip;
            }
            set
            {
                this._tooltip = value;
            }
        }
        
        // 
        public int Maxrank
        {
            get
            {
                return this._maxrank;
            }
            set
            {
                this._maxrank = value;
            }
        }
        
        // 
        public string CostBurn
        {
            get
            {
                return this._costBurn;
            }
            set
            {
                this._costBurn = value;
            }
        }
        
        // 
        public string RangeBurn
        {
            get
            {
                return this._rangeBurn;
            }
            set
            {
                this._rangeBurn = value;
            }
        }
        
        // This field is either a List of Integer or the String 'self' for spells that target one's own champion.
        public object Range
        {
            get
            {
                return this._range;
            }
            set
            {
                this._range = value;
            }
        }
        
        // 
        public List<double> Cooldown
        {
            get
            {
                return this._cooldown;
            }
            set
            {
                this._cooldown = value;
            }
        }
        
        // 
        public List<int> Cost
        {
            get
            {
                return this._cost;
            }
            set
            {
                this._cost = value;
            }
        }
        
        // 
        public string Key
        {
            get
            {
                return this._key;
            }
            set
            {
                this._key = value;
            }
        }
        
        // 
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
        
        // 
        public List<string> EffectBurn
        {
            get
            {
                return this._effectBurn;
            }
            set
            {
                this._effectBurn = value;
            }
        }
        
        // 
        public List<ImageDtoStatic> Altimages
        {
            get
            {
                return this._altimages;
            }
            set
            {
                this._altimages = value;
            }
        }
        
        // 
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
    }
}
