//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains champion data.
    public class ChampionDtoStatic
    {
        
        // 
        [JsonProperty("info")]
        private InfoDtoStatic _info;
        
        // 
        [JsonProperty("enemytips")]
        private List<string> _enemytips;
        
        // 
        [JsonProperty("stats")]
        private StatsDtoStatic _stats;
        
        // 
        [JsonProperty("name")]
        private string _name;
        
        // 
        [JsonProperty("title")]
        private string _title;
        
        // 
        [JsonProperty("image")]
        private ImageDtoStatic _image;
        
        // 
        [JsonProperty("tags")]
        private List<string> _tags;
        
        // 
        [JsonProperty("partype")]
        private string _partype;
        
        // 
        [JsonProperty("skins")]
        private List<SkinDtoStatic> _skins;
        
        // 
        [JsonProperty("passive")]
        private PassiveDtoStatic _passive;
        
        // 
        [JsonProperty("recommended")]
        private List<RecommendedDtoStatic> _recommended;
        
        // 
        [JsonProperty("allytips")]
        private List<string> _allytips;
        
        // 
        [JsonProperty("key")]
        private string _key;
        
        // 
        [JsonProperty("lore")]
        private string _lore;
        
        // 
        [JsonProperty("id")]
        private int _id;
        
        // 
        [JsonProperty("blurb")]
        private string _blurb;
        
        // 
        [JsonProperty("spells")]
        private List<ChampionSpellDtoStatic> _spells;
        
        // 
        public InfoDtoStatic Info
        {
            get
            {
                return this._info;
            }
            set
            {
                this._info = value;
            }
        }
        
        // 
        public List<string> Enemytips
        {
            get
            {
                return this._enemytips;
            }
            set
            {
                this._enemytips = value;
            }
        }
        
        // 
        public StatsDtoStatic Stats
        {
            get
            {
                return this._stats;
            }
            set
            {
                this._stats = value;
            }
        }
        
        // 
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        // 
        public string Title
        {
            get
            {
                return this._title;
            }
            set
            {
                this._title = value;
            }
        }
        
        // 
        public ImageDtoStatic Image
        {
            get
            {
                return this._image;
            }
            set
            {
                this._image = value;
            }
        }
        
        // 
        public List<string> Tags
        {
            get
            {
                return this._tags;
            }
            set
            {
                this._tags = value;
            }
        }
        
        // 
        public string Partype
        {
            get
            {
                return this._partype;
            }
            set
            {
                this._partype = value;
            }
        }
        
        // 
        public List<SkinDtoStatic> Skins
        {
            get
            {
                return this._skins;
            }
            set
            {
                this._skins = value;
            }
        }
        
        // 
        public PassiveDtoStatic Passive
        {
            get
            {
                return this._passive;
            }
            set
            {
                this._passive = value;
            }
        }
        
        // 
        public List<RecommendedDtoStatic> Recommended
        {
            get
            {
                return this._recommended;
            }
            set
            {
                this._recommended = value;
            }
        }
        
        // 
        public List<string> Allytips
        {
            get
            {
                return this._allytips;
            }
            set
            {
                this._allytips = value;
            }
        }
        
        // 
        public string Key
        {
            get
            {
                return this._key;
            }
            set
            {
                this._key = value;
            }
        }
        
        // 
        public string Lore
        {
            get
            {
                return this._lore;
            }
            set
            {
                this._lore = value;
            }
        }
        
        // 
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        // 
        public string Blurb
        {
            get
            {
                return this._blurb;
            }
            set
            {
                this._blurb = value;
            }
        }
        
        // 
        public List<ChampionSpellDtoStatic> Spells
        {
            get
            {
                return this._spells;
            }
            set
            {
                this._spells = value;
            }
        }
    }
}
