//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains item gold data.
    public class GoldDtoStatic
    {
        
        // 
        [JsonProperty("sell")]
        private int _sell;
        
        // 
        [JsonProperty("total")]
        private int _total;
        
        // 
        [JsonProperty("base")]
        private int _base;
        
        // 
        [JsonProperty("purchasable")]
        private bool _purchasable;
        
        // 
        public int Sell
        {
            get
            {
                return this._sell;
            }
            set
            {
                this._sell = value;
            }
        }
        
        // 
        public int Total
        {
            get
            {
                return this._total;
            }
            set
            {
                this._total = value;
            }
        }
        
        // 
        public int Base
        {
            get
            {
                return this._base;
            }
            set
            {
                this._base = value;
            }
        }
        
        // 
        public bool Purchasable
        {
            get
            {
                return this._purchasable;
            }
            set
            {
                this._purchasable = value;
            }
        }
    }
}
