//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains item group data.
    public class GroupDtoStatic
    {
        
        // 
        [JsonProperty("MaxGroupOwnable")]
        private string _maxGroupOwnable;
        
        // 
        [JsonProperty("key")]
        private string _key;
        
        // 
        public string ReName_MaxGroupOwnable
        {
            get
            {
                return this._maxGroupOwnable;
            }
            set
            {
                this._maxGroupOwnable = value;
            }
        }
        
        // 
        public string Key
        {
            get
            {
                return this._key;
            }
            set
            {
                this._key = value;
            }
        }
    }
}
