//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains image data.
    public class ImageDtoStatic
    {
        
        // 
        [JsonProperty("full")]
        private string _full;
        
        // 
        [JsonProperty("group")]
        private string _group;
        
        // 
        [JsonProperty("sprite")]
        private string _sprite;
        
        // 
        [JsonProperty("h")]
        private int _h;
        
        // 
        [JsonProperty("w")]
        private int _w;
        
        // 
        [JsonProperty("y")]
        private int _y;
        
        // 
        [JsonProperty("x")]
        private int _x;
        
        // 
        public string Full
        {
            get
            {
                return this._full;
            }
            set
            {
                this._full = value;
            }
        }
        
        // 
        public string Group
        {
            get
            {
                return this._group;
            }
            set
            {
                this._group = value;
            }
        }
        
        // 
        public string Sprite
        {
            get
            {
                return this._sprite;
            }
            set
            {
                this._sprite = value;
            }
        }
        
        // 
        public int H
        {
            get
            {
                return this._h;
            }
            set
            {
                this._h = value;
            }
        }
        
        // 
        public int W
        {
            get
            {
                return this._w;
            }
            set
            {
                this._w = value;
            }
        }
        
        // 
        public int Y
        {
            get
            {
                return this._y;
            }
            set
            {
                this._y = value;
            }
        }
        
        // 
        public int X
        {
            get
            {
                return this._x;
            }
            set
            {
                this._x = value;
            }
        }
    }
}
