//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains champion information.
    public class InfoDtoStatic
    {
        
        // 
        [JsonProperty("difficulty")]
        private int _difficulty;
        
        // 
        [JsonProperty("attack")]
        private int _attack;
        
        // 
        [JsonProperty("defense")]
        private int _defense;
        
        // 
        [JsonProperty("magic")]
        private int _magic;
        
        // 
        public int Difficulty
        {
            get
            {
                return this._difficulty;
            }
            set
            {
                this._difficulty = value;
            }
        }
        
        // 
        public int Attack
        {
            get
            {
                return this._attack;
            }
            set
            {
                this._attack = value;
            }
        }
        
        // 
        public int Defense
        {
            get
            {
                return this._defense;
            }
            set
            {
                this._defense = value;
            }
        }
        
        // 
        public int Magic
        {
            get
            {
                return this._magic;
            }
            set
            {
                this._magic = value;
            }
        }
    }
}
