//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains stats for inventory (e.g., runes and items).
    public class InventoryDataStatsDtoStatic
    {
        
        // 
        [JsonProperty("PercentCritDamageMod")]
        private double _percentCritDamageMod;
        
        // 
        [JsonProperty("PercentSpellBlockMod")]
        private double _percentSpellBlockMod;
        
        // 
        [JsonProperty("PercentHPRegenMod")]
        private double _percentHPRegenMod;
        
        // 
        [JsonProperty("PercentMovementSpeedMod")]
        private double _percentMovementSpeedMod;
        
        // 
        [JsonProperty("FlatSpellBlockMod")]
        private double _flatSpellBlockMod;
        
        // 
        [JsonProperty("FlatCritDamageMod")]
        private double _flatCritDamageMod;
        
        // 
        [JsonProperty("FlatEnergyPoolMod")]
        private double _flatEnergyPoolMod;
        
        // 
        [JsonProperty("PercentLifeStealMod")]
        private double _percentLifeStealMod;
        
        // 
        [JsonProperty("FlatMPPoolMod")]
        private double _flatMPPoolMod;
        
        // 
        [JsonProperty("FlatMovementSpeedMod")]
        private double _flatMovementSpeedMod;
        
        // 
        [JsonProperty("PercentAttackSpeedMod")]
        private double _percentAttackSpeedMod;
        
        // 
        [JsonProperty("FlatBlockMod")]
        private double _flatBlockMod;
        
        // 
        [JsonProperty("PercentBlockMod")]
        private double _percentBlockMod;
        
        // 
        [JsonProperty("FlatEnergyRegenMod")]
        private double _flatEnergyRegenMod;
        
        // 
        [JsonProperty("PercentSpellVampMod")]
        private double _percentSpellVampMod;
        
        // 
        [JsonProperty("FlatMPRegenMod")]
        private double _flatMPRegenMod;
        
        // 
        [JsonProperty("PercentDodgeMod")]
        private double _percentDodgeMod;
        
        // 
        [JsonProperty("FlatAttackSpeedMod")]
        private double _flatAttackSpeedMod;
        
        // 
        [JsonProperty("FlatArmorMod")]
        private double _flatArmorMod;
        
        // 
        [JsonProperty("FlatHPRegenMod")]
        private double _flatHPRegenMod;
        
        // 
        [JsonProperty("PercentMagicDamageMod")]
        private double _percentMagicDamageMod;
        
        // 
        [JsonProperty("PercentMPPoolMod")]
        private double _percentMPPoolMod;
        
        // 
        [JsonProperty("FlatMagicDamageMod")]
        private double _flatMagicDamageMod;
        
        // 
        [JsonProperty("PercentMPRegenMod")]
        private double _percentMPRegenMod;
        
        // 
        [JsonProperty("PercentPhysicalDamageMod")]
        private double _percentPhysicalDamageMod;
        
        // 
        [JsonProperty("FlatPhysicalDamageMod")]
        private double _flatPhysicalDamageMod;
        
        // 
        [JsonProperty("PercentHPPoolMod")]
        private double _percentHPPoolMod;
        
        // 
        [JsonProperty("PercentArmorMod")]
        private double _percentArmorMod;
        
        // 
        [JsonProperty("PercentCritChanceMod")]
        private double _percentCritChanceMod;
        
        // 
        [JsonProperty("PercentEXPBonus")]
        private double _percentEXPBonus;
        
        // 
        [JsonProperty("FlatHPPoolMod")]
        private double _flatHPPoolMod;
        
        // 
        [JsonProperty("FlatCritChanceMod")]
        private double _flatCritChanceMod;
        
        // 
        [JsonProperty("FlatEXPBonus")]
        private double _flatEXPBonus;
        
        // 
        public double ReName_PercentCritDamageMod
        {
            get
            {
                return this._percentCritDamageMod;
            }
            set
            {
                this._percentCritDamageMod = value;
            }
        }
        
        // 
        public double ReName_PercentSpellBlockMod
        {
            get
            {
                return this._percentSpellBlockMod;
            }
            set
            {
                this._percentSpellBlockMod = value;
            }
        }
        
        // 
        public double ReName_PercentHPRegenMod
        {
            get
            {
                return this._percentHPRegenMod;
            }
            set
            {
                this._percentHPRegenMod = value;
            }
        }
        
        // 
        public double ReName_PercentMovementSpeedMod
        {
            get
            {
                return this._percentMovementSpeedMod;
            }
            set
            {
                this._percentMovementSpeedMod = value;
            }
        }
        
        // 
        public double ReName_FlatSpellBlockMod
        {
            get
            {
                return this._flatSpellBlockMod;
            }
            set
            {
                this._flatSpellBlockMod = value;
            }
        }
        
        // 
        public double ReName_FlatCritDamageMod
        {
            get
            {
                return this._flatCritDamageMod;
            }
            set
            {
                this._flatCritDamageMod = value;
            }
        }
        
        // 
        public double ReName_FlatEnergyPoolMod
        {
            get
            {
                return this._flatEnergyPoolMod;
            }
            set
            {
                this._flatEnergyPoolMod = value;
            }
        }
        
        // 
        public double ReName_PercentLifeStealMod
        {
            get
            {
                return this._percentLifeStealMod;
            }
            set
            {
                this._percentLifeStealMod = value;
            }
        }
        
        // 
        public double ReName_FlatMPPoolMod
        {
            get
            {
                return this._flatMPPoolMod;
            }
            set
            {
                this._flatMPPoolMod = value;
            }
        }
        
        // 
        public double ReName_FlatMovementSpeedMod
        {
            get
            {
                return this._flatMovementSpeedMod;
            }
            set
            {
                this._flatMovementSpeedMod = value;
            }
        }
        
        // 
        public double ReName_PercentAttackSpeedMod
        {
            get
            {
                return this._percentAttackSpeedMod;
            }
            set
            {
                this._percentAttackSpeedMod = value;
            }
        }
        
        // 
        public double ReName_FlatBlockMod
        {
            get
            {
                return this._flatBlockMod;
            }
            set
            {
                this._flatBlockMod = value;
            }
        }
        
        // 
        public double ReName_PercentBlockMod
        {
            get
            {
                return this._percentBlockMod;
            }
            set
            {
                this._percentBlockMod = value;
            }
        }
        
        // 
        public double ReName_FlatEnergyRegenMod
        {
            get
            {
                return this._flatEnergyRegenMod;
            }
            set
            {
                this._flatEnergyRegenMod = value;
            }
        }
        
        // 
        public double ReName_PercentSpellVampMod
        {
            get
            {
                return this._percentSpellVampMod;
            }
            set
            {
                this._percentSpellVampMod = value;
            }
        }
        
        // 
        public double ReName_FlatMPRegenMod
        {
            get
            {
                return this._flatMPRegenMod;
            }
            set
            {
                this._flatMPRegenMod = value;
            }
        }
        
        // 
        public double ReName_PercentDodgeMod
        {
            get
            {
                return this._percentDodgeMod;
            }
            set
            {
                this._percentDodgeMod = value;
            }
        }
        
        // 
        public double ReName_FlatAttackSpeedMod
        {
            get
            {
                return this._flatAttackSpeedMod;
            }
            set
            {
                this._flatAttackSpeedMod = value;
            }
        }
        
        // 
        public double ReName_FlatArmorMod
        {
            get
            {
                return this._flatArmorMod;
            }
            set
            {
                this._flatArmorMod = value;
            }
        }
        
        // 
        public double ReName_FlatHPRegenMod
        {
            get
            {
                return this._flatHPRegenMod;
            }
            set
            {
                this._flatHPRegenMod = value;
            }
        }
        
        // 
        public double ReName_PercentMagicDamageMod
        {
            get
            {
                return this._percentMagicDamageMod;
            }
            set
            {
                this._percentMagicDamageMod = value;
            }
        }
        
        // 
        public double ReName_PercentMPPoolMod
        {
            get
            {
                return this._percentMPPoolMod;
            }
            set
            {
                this._percentMPPoolMod = value;
            }
        }
        
        // 
        public double ReName_FlatMagicDamageMod
        {
            get
            {
                return this._flatMagicDamageMod;
            }
            set
            {
                this._flatMagicDamageMod = value;
            }
        }
        
        // 
        public double ReName_PercentMPRegenMod
        {
            get
            {
                return this._percentMPRegenMod;
            }
            set
            {
                this._percentMPRegenMod = value;
            }
        }
        
        // 
        public double ReName_PercentPhysicalDamageMod
        {
            get
            {
                return this._percentPhysicalDamageMod;
            }
            set
            {
                this._percentPhysicalDamageMod = value;
            }
        }
        
        // 
        public double ReName_FlatPhysicalDamageMod
        {
            get
            {
                return this._flatPhysicalDamageMod;
            }
            set
            {
                this._flatPhysicalDamageMod = value;
            }
        }
        
        // 
        public double ReName_PercentHPPoolMod
        {
            get
            {
                return this._percentHPPoolMod;
            }
            set
            {
                this._percentHPPoolMod = value;
            }
        }
        
        // 
        public double ReName_PercentArmorMod
        {
            get
            {
                return this._percentArmorMod;
            }
            set
            {
                this._percentArmorMod = value;
            }
        }
        
        // 
        public double ReName_PercentCritChanceMod
        {
            get
            {
                return this._percentCritChanceMod;
            }
            set
            {
                this._percentCritChanceMod = value;
            }
        }
        
        // 
        public double ReName_PercentEXPBonus
        {
            get
            {
                return this._percentEXPBonus;
            }
            set
            {
                this._percentEXPBonus = value;
            }
        }
        
        // 
        public double ReName_FlatHPPoolMod
        {
            get
            {
                return this._flatHPPoolMod;
            }
            set
            {
                this._flatHPPoolMod = value;
            }
        }
        
        // 
        public double ReName_FlatCritChanceMod
        {
            get
            {
                return this._flatCritChanceMod;
            }
            set
            {
                this._flatCritChanceMod = value;
            }
        }
        
        // 
        public double ReName_FlatEXPBonus
        {
            get
            {
                return this._flatEXPBonus;
            }
            set
            {
                this._flatEXPBonus = value;
            }
        }
    }
}
