//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains item data.
    public class ItemDtoStatic
    {
        
        // 
        [JsonProperty("gold")]
        private GoldDtoStatic _gold;
        
        // 
        [JsonProperty("plaintext")]
        private string _plaintext;
        
        // 
        [JsonProperty("hideFromAll")]
        private bool _hideFromAll;
        
        // 
        [JsonProperty("inStore")]
        private bool _inStore;
        
        // 
        [JsonProperty("into")]
        private List<string> _into;
        
        // 
        [JsonProperty("id")]
        private int _id;
        
        // 
        [JsonProperty("stats")]
        private InventoryDataStatsDtoStatic _stats;
        
        // 
        [JsonProperty("colloq")]
        private string _colloq;
        
        // 
        [JsonProperty("maps")]
        private System.Collections.Generic.Dictionary<string, System.Boolean> _maps;
        
        // 
        [JsonProperty("specialRecipe")]
        private int _specialRecipe;
        
        // 
        [JsonProperty("image")]
        private ImageDtoStatic _image;
        
        // 
        [JsonProperty("description")]
        private string _description;
        
        // 
        [JsonProperty("tags")]
        private List<string> _tags;
        
        // 
        [JsonProperty("effect")]
        private System.Collections.Generic.Dictionary<string, string> _effect;
        
        // 
        [JsonProperty("requiredChampion")]
        private string _requiredChampion;
        
        // 
        [JsonProperty("from")]
        private List<string> _from;
        
        // 
        [JsonProperty("group")]
        private string _group;
        
        // 
        [JsonProperty("consumeOnFull")]
        private bool _consumeOnFull;
        
        // 
        [JsonProperty("name")]
        private string _name;
        
        // 
        [JsonProperty("consumed")]
        private bool _consumed;
        
        // 
        [JsonProperty("sanitizedDescription")]
        private string _sanitizedDescription;
        
        // 
        [JsonProperty("depth")]
        private int _depth;
        
        // 
        [JsonProperty("stacks")]
        private int _stacks;
        
        // 
        public GoldDtoStatic Gold
        {
            get
            {
                return this._gold;
            }
            set
            {
                this._gold = value;
            }
        }
        
        // 
        public string Plaintext
        {
            get
            {
                return this._plaintext;
            }
            set
            {
                this._plaintext = value;
            }
        }
        
        // 
        public bool HideFromAll
        {
            get
            {
                return this._hideFromAll;
            }
            set
            {
                this._hideFromAll = value;
            }
        }
        
        // 
        public bool InStore
        {
            get
            {
                return this._inStore;
            }
            set
            {
                this._inStore = value;
            }
        }
        
        // 
        public List<string> Into
        {
            get
            {
                return this._into;
            }
            set
            {
                this._into = value;
            }
        }
        
        // 
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        // 
        public InventoryDataStatsDtoStatic Stats
        {
            get
            {
                return this._stats;
            }
            set
            {
                this._stats = value;
            }
        }
        
        // 
        public string Colloq
        {
            get
            {
                return this._colloq;
            }
            set
            {
                this._colloq = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<string, System.Boolean> Maps
        {
            get
            {
                return this._maps;
            }
            set
            {
                this._maps = value;
            }
        }
        
        // 
        public int SpecialRecipe
        {
            get
            {
                return this._specialRecipe;
            }
            set
            {
                this._specialRecipe = value;
            }
        }
        
        // 
        public ImageDtoStatic Image
        {
            get
            {
                return this._image;
            }
            set
            {
                this._image = value;
            }
        }
        
        // 
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
        
        // 
        public List<string> Tags
        {
            get
            {
                return this._tags;
            }
            set
            {
                this._tags = value;
            }
        }
        
        // 
        public System.Collections.Generic.Dictionary<string, string> Effect
        {
            get
            {
                return this._effect;
            }
            set
            {
                this._effect = value;
            }
        }
        
        // 
        public string RequiredChampion
        {
            get
            {
                return this._requiredChampion;
            }
            set
            {
                this._requiredChampion = value;
            }
        }
        
        // 
        public List<string> From
        {
            get
            {
                return this._from;
            }
            set
            {
                this._from = value;
            }
        }
        
        // 
        public string Group
        {
            get
            {
                return this._group;
            }
            set
            {
                this._group = value;
            }
        }
        
        // 
        public bool ConsumeOnFull
        {
            get
            {
                return this._consumeOnFull;
            }
            set
            {
                this._consumeOnFull = value;
            }
        }
        
        // 
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        // 
        public bool Consumed
        {
            get
            {
                return this._consumed;
            }
            set
            {
                this._consumed = value;
            }
        }
        
        // 
        public string SanitizedDescription
        {
            get
            {
                return this._sanitizedDescription;
            }
            set
            {
                this._sanitizedDescription = value;
            }
        }
        
        // 
        public int Depth
        {
            get
            {
                return this._depth;
            }
            set
            {
                this._depth = value;
            }
        }
        
        // 
        public int Stacks
        {
            get
            {
                return this._stacks;
            }
            set
            {
                this._stacks = value;
            }
        }
    }
}
