//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains item tree data.
    public class ItemTreeDtoStatic
    {
        
        // 
        [JsonProperty("header")]
        private string _header;
        
        // 
        [JsonProperty("tags")]
        private List<string> _tags;
        
        // 
        public string Header
        {
            get
            {
                return this._header;
            }
            set
            {
                this._header = value;
            }
        }
        
        // 
        public List<string> Tags
        {
            get
            {
                return this._tags;
            }
            set
            {
                this._tags = value;
            }
        }
    }
}
