//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains champion level tip data.
    public class LevelTipDtoStatic
    {
        
        // 
        [JsonProperty("effect")]
        private List<string> _effect;
        
        // 
        [JsonProperty("label")]
        private List<string> _label;
        
        // 
        public List<string> Effect
        {
            get
            {
                return this._effect;
            }
            set
            {
                this._effect = value;
            }
        }
        
        // 
        public List<string> Label
        {
            get
            {
                return this._label;
            }
            set
            {
                this._label = value;
            }
        }
    }
}
