//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains mastery tree item data.
    public class MasteryTreeItemDtoStatic
    {
        
        // 
        [JsonProperty("masteryId")]
        private int _masteryId;
        
        // 
        [JsonProperty("prereq")]
        private string _prereq;
        
        // 
        public int MasteryId
        {
            get
            {
                return this._masteryId;
            }
            set
            {
                this._masteryId = value;
            }
        }
        
        // 
        public string Prereq
        {
            get
            {
                return this._prereq;
            }
            set
            {
                this._prereq = value;
            }
        }
    }
}
