//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains mastery tree list data.
    public class MasteryTreeListDtoStatic
    {
        
        // 
        [JsonProperty("masteryTreeItems")]
        private List<MasteryTreeItemDtoStatic> _masteryTreeItems;
        
        // 
        public List<MasteryTreeItemDtoStatic> MasteryTreeItems
        {
            get
            {
                return this._masteryTreeItems;
            }
            set
            {
                this._masteryTreeItems = value;
            }
        }
    }
}
