//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains meta data.
    public class MetaDataDtoStatic
    {
        
        // 
        [JsonProperty("tier")]
        private string _tier;
        
        // 
        [JsonProperty("type")]
        private string _type;
        
        // 
        [JsonProperty("isRune")]
        private bool _isRune;
        
        // 
        public string Tier
        {
            get
            {
                return this._tier;
            }
            set
            {
                this._tier = value;
            }
        }
        
        // 
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        // 
        public bool IsRune
        {
            get
            {
                return this._isRune;
            }
            set
            {
                this._isRune = value;
            }
        }
    }
}
