//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains champion recommended data.
    public class RecommendedDtoStatic
    {
        
        // 
        [JsonProperty("map")]
        private string _map;
        
        // 
        [JsonProperty("blocks")]
        private List<BlockDtoStatic> _blocks;
        
        // 
        [JsonProperty("champion")]
        private string _champion;
        
        // 
        [JsonProperty("title")]
        private string _title;
        
        // 
        [JsonProperty("priority")]
        private bool _priority;
        
        // 
        [JsonProperty("mode")]
        private string _mode;
        
        // 
        [JsonProperty("type")]
        private string _type;
        
        // 
        public string Map
        {
            get
            {
                return this._map;
            }
            set
            {
                this._map = value;
            }
        }
        
        // 
        public List<BlockDtoStatic> Blocks
        {
            get
            {
                return this._blocks;
            }
            set
            {
                this._blocks = value;
            }
        }
        
        // 
        public string Champion
        {
            get
            {
                return this._champion;
            }
            set
            {
                this._champion = value;
            }
        }
        
        // 
        public string Title
        {
            get
            {
                return this._title;
            }
            set
            {
                this._title = value;
            }
        }
        
        // 
        public bool Priority
        {
            get
            {
                return this._priority;
            }
            set
            {
                this._priority = value;
            }
        }
        
        // 
        public string Mode
        {
            get
            {
                return this._mode;
            }
            set
            {
                this._mode = value;
            }
        }
        
        // 
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
    }
}
