//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains rune data.
    public class RuneDtoStatic
    {
        
        // 
        [JsonProperty("stats")]
        private RuneStatsDtoStatic _stats;
        
        // 
        [JsonProperty("name")]
        private string _name;
        
        // 
        [JsonProperty("tags")]
        private List<string> _tags;
        
        // 
        [JsonProperty("image")]
        private ImageDtoStatic _image;
        
        // 
        [JsonProperty("sanitizedDescription")]
        private string _sanitizedDescription;
        
        // 
        [JsonProperty("rune")]
        private MetaDataDtoStatic _rune;
        
        // 
        [JsonProperty("id")]
        private int _id;
        
        // 
        [JsonProperty("description")]
        private string _description;
        
        // 
        public RuneStatsDtoStatic Stats
        {
            get
            {
                return this._stats;
            }
            set
            {
                this._stats = value;
            }
        }
        
        // 
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        // 
        public List<string> Tags
        {
            get
            {
                return this._tags;
            }
            set
            {
                this._tags = value;
            }
        }
        
        // 
        public ImageDtoStatic Image
        {
            get
            {
                return this._image;
            }
            set
            {
                this._image = value;
            }
        }
        
        // 
        public string SanitizedDescription
        {
            get
            {
                return this._sanitizedDescription;
            }
            set
            {
                this._sanitizedDescription = value;
            }
        }
        
        // 
        public MetaDataDtoStatic Rune
        {
            get
            {
                return this._rune;
            }
            set
            {
                this._rune = value;
            }
        }
        
        // 
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        // 
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
    }
}
