//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains stats for runes.
    public class RuneStatsDtoStatic
    {
        
        // 
        [JsonProperty("PercentTimeDeadModPerLevel")]
        private double _percentTimeDeadModPerLevel;
        
        // 
        [JsonProperty("PercentArmorPenetrationModPerLevel")]
        private double _percentArmorPenetrationModPerLevel;
        
        // 
        [JsonProperty("PercentCritDamageMod")]
        private double _percentCritDamageMod;
        
        // 
        [JsonProperty("PercentSpellBlockMod")]
        private double _percentSpellBlockMod;
        
        // 
        [JsonProperty("PercentHPRegenMod")]
        private double _percentHPRegenMod;
        
        // 
        [JsonProperty("PercentMovementSpeedMod")]
        private double _percentMovementSpeedMod;
        
        // 
        [JsonProperty("FlatSpellBlockMod")]
        private double _flatSpellBlockMod;
        
        // 
        [JsonProperty("FlatEnergyRegenModPerLevel")]
        private double _flatEnergyRegenModPerLevel;
        
        // 
        [JsonProperty("FlatEnergyPoolMod")]
        private double _flatEnergyPoolMod;
        
        // 
        [JsonProperty("FlatMagicPenetrationModPerLevel")]
        private double _flatMagicPenetrationModPerLevel;
        
        // 
        [JsonProperty("PercentLifeStealMod")]
        private double _percentLifeStealMod;
        
        // 
        [JsonProperty("FlatMPPoolMod")]
        private double _flatMPPoolMod;
        
        // 
        [JsonProperty("PercentCooldownMod")]
        private double _percentCooldownMod;
        
        // 
        [JsonProperty("PercentMagicPenetrationMod")]
        private double _percentMagicPenetrationMod;
        
        // 
        [JsonProperty("FlatArmorPenetrationModPerLevel")]
        private double _flatArmorPenetrationModPerLevel;
        
        // 
        [JsonProperty("FlatMovementSpeedMod")]
        private double _flatMovementSpeedMod;
        
        // 
        [JsonProperty("FlatTimeDeadModPerLevel")]
        private double _flatTimeDeadModPerLevel;
        
        // 
        [JsonProperty("FlatArmorModPerLevel")]
        private double _flatArmorModPerLevel;
        
        // 
        [JsonProperty("PercentAttackSpeedMod")]
        private double _percentAttackSpeedMod;
        
        // 
        [JsonProperty("FlatDodgeModPerLevel")]
        private double _flatDodgeModPerLevel;
        
        // 
        [JsonProperty("PercentMagicDamageMod")]
        private double _percentMagicDamageMod;
        
        // 
        [JsonProperty("PercentBlockMod")]
        private double _percentBlockMod;
        
        // 
        [JsonProperty("FlatDodgeMod")]
        private double _flatDodgeMod;
        
        // 
        [JsonProperty("FlatEnergyRegenMod")]
        private double _flatEnergyRegenMod;
        
        // 
        [JsonProperty("FlatHPModPerLevel")]
        private double _flatHPModPerLevel;
        
        // 
        [JsonProperty("PercentAttackSpeedModPerLevel")]
        private double _percentAttackSpeedModPerLevel;
        
        // 
        [JsonProperty("PercentSpellVampMod")]
        private double _percentSpellVampMod;
        
        // 
        [JsonProperty("FlatMPRegenMod")]
        private double _flatMPRegenMod;
        
        // 
        [JsonProperty("PercentHPPoolMod")]
        private double _percentHPPoolMod;
        
        // 
        [JsonProperty("PercentDodgeMod")]
        private double _percentDodgeMod;
        
        // 
        [JsonProperty("FlatAttackSpeedMod")]
        private double _flatAttackSpeedMod;
        
        // 
        [JsonProperty("FlatArmorMod")]
        private double _flatArmorMod;
        
        // 
        [JsonProperty("FlatMagicDamageModPerLevel")]
        private double _flatMagicDamageModPerLevel;
        
        // 
        [JsonProperty("FlatHPRegenMod")]
        private double _flatHPRegenMod;
        
        // 
        [JsonProperty("PercentPhysicalDamageMod")]
        private double _percentPhysicalDamageMod;
        
        // 
        [JsonProperty("FlatCritChanceModPerLevel")]
        private double _flatCritChanceModPerLevel;
        
        // 
        [JsonProperty("FlatSpellBlockModPerLevel")]
        private double _flatSpellBlockModPerLevel;
        
        // 
        [JsonProperty("PercentTimeDeadMod")]
        private double _percentTimeDeadMod;
        
        // 
        [JsonProperty("FlatBlockMod")]
        private double _flatBlockMod;
        
        // 
        [JsonProperty("PercentMPPoolMod")]
        private double _percentMPPoolMod;
        
        // 
        [JsonProperty("FlatMagicDamageMod")]
        private double _flatMagicDamageMod;
        
        // 
        [JsonProperty("PercentMPRegenMod")]
        private double _percentMPRegenMod;
        
        // 
        [JsonProperty("PercentMovementSpeedModPerLevel")]
        private double _percentMovementSpeedModPerLevel;
        
        // 
        [JsonProperty("PercentCooldownModPerLevel")]
        private double _percentCooldownModPerLevel;
        
        // 
        [JsonProperty("FlatMPModPerLevel")]
        private double _flatMPModPerLevel;
        
        // 
        [JsonProperty("FlatEnergyModPerLevel")]
        private double _flatEnergyModPerLevel;
        
        // 
        [JsonProperty("FlatPhysicalDamageMod")]
        private double _flatPhysicalDamageMod;
        
        // 
        [JsonProperty("FlatHPRegenModPerLevel")]
        private double _flatHPRegenModPerLevel;
        
        // 
        [JsonProperty("FlatCritDamageMod")]
        private double _flatCritDamageMod;
        
        // 
        [JsonProperty("PercentArmorMod")]
        private double _percentArmorMod;
        
        // 
        [JsonProperty("FlatMagicPenetrationMod")]
        private double _flatMagicPenetrationMod;
        
        // 
        [JsonProperty("PercentCritChanceMod")]
        private double _percentCritChanceMod;
        
        // 
        [JsonProperty("FlatPhysicalDamageModPerLevel")]
        private double _flatPhysicalDamageModPerLevel;
        
        // 
        [JsonProperty("PercentArmorPenetrationMod")]
        private double _percentArmorPenetrationMod;
        
        // 
        [JsonProperty("PercentEXPBonus")]
        private double _percentEXPBonus;
        
        // 
        [JsonProperty("FlatMPRegenModPerLevel")]
        private double _flatMPRegenModPerLevel;
        
        // 
        [JsonProperty("PercentMagicPenetrationModPerLevel")]
        private double _percentMagicPenetrationModPerLevel;
        
        // 
        [JsonProperty("FlatTimeDeadMod")]
        private double _flatTimeDeadMod;
        
        // 
        [JsonProperty("FlatMovementSpeedModPerLevel")]
        private double _flatMovementSpeedModPerLevel;
        
        // 
        [JsonProperty("FlatGoldPer10Mod")]
        private double _flatGoldPer10Mod;
        
        // 
        [JsonProperty("FlatArmorPenetrationMod")]
        private double _flatArmorPenetrationMod;
        
        // 
        [JsonProperty("FlatCritDamageModPerLevel")]
        private double _flatCritDamageModPerLevel;
        
        // 
        [JsonProperty("FlatHPPoolMod")]
        private double _flatHPPoolMod;
        
        // 
        [JsonProperty("FlatCritChanceMod")]
        private double _flatCritChanceMod;
        
        // 
        [JsonProperty("FlatEXPBonus")]
        private double _flatEXPBonus;
        
        // 
        public double ReName_PercentTimeDeadModPerLevel
        {
            get
            {
                return this._percentTimeDeadModPerLevel;
            }
            set
            {
                this._percentTimeDeadModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentArmorPenetrationModPerLevel
        {
            get
            {
                return this._percentArmorPenetrationModPerLevel;
            }
            set
            {
                this._percentArmorPenetrationModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentCritDamageMod
        {
            get
            {
                return this._percentCritDamageMod;
            }
            set
            {
                this._percentCritDamageMod = value;
            }
        }
        
        // 
        public double ReName_PercentSpellBlockMod
        {
            get
            {
                return this._percentSpellBlockMod;
            }
            set
            {
                this._percentSpellBlockMod = value;
            }
        }
        
        // 
        public double ReName_PercentHPRegenMod
        {
            get
            {
                return this._percentHPRegenMod;
            }
            set
            {
                this._percentHPRegenMod = value;
            }
        }
        
        // 
        public double ReName_PercentMovementSpeedMod
        {
            get
            {
                return this._percentMovementSpeedMod;
            }
            set
            {
                this._percentMovementSpeedMod = value;
            }
        }
        
        // 
        public double ReName_FlatSpellBlockMod
        {
            get
            {
                return this._flatSpellBlockMod;
            }
            set
            {
                this._flatSpellBlockMod = value;
            }
        }
        
        // 
        public double ReName_FlatEnergyRegenModPerLevel
        {
            get
            {
                return this._flatEnergyRegenModPerLevel;
            }
            set
            {
                this._flatEnergyRegenModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatEnergyPoolMod
        {
            get
            {
                return this._flatEnergyPoolMod;
            }
            set
            {
                this._flatEnergyPoolMod = value;
            }
        }
        
        // 
        public double ReName_FlatMagicPenetrationModPerLevel
        {
            get
            {
                return this._flatMagicPenetrationModPerLevel;
            }
            set
            {
                this._flatMagicPenetrationModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentLifeStealMod
        {
            get
            {
                return this._percentLifeStealMod;
            }
            set
            {
                this._percentLifeStealMod = value;
            }
        }
        
        // 
        public double ReName_FlatMPPoolMod
        {
            get
            {
                return this._flatMPPoolMod;
            }
            set
            {
                this._flatMPPoolMod = value;
            }
        }
        
        // 
        public double ReName_PercentCooldownMod
        {
            get
            {
                return this._percentCooldownMod;
            }
            set
            {
                this._percentCooldownMod = value;
            }
        }
        
        // 
        public double ReName_PercentMagicPenetrationMod
        {
            get
            {
                return this._percentMagicPenetrationMod;
            }
            set
            {
                this._percentMagicPenetrationMod = value;
            }
        }
        
        // 
        public double ReName_FlatArmorPenetrationModPerLevel
        {
            get
            {
                return this._flatArmorPenetrationModPerLevel;
            }
            set
            {
                this._flatArmorPenetrationModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatMovementSpeedMod
        {
            get
            {
                return this._flatMovementSpeedMod;
            }
            set
            {
                this._flatMovementSpeedMod = value;
            }
        }
        
        // 
        public double ReName_FlatTimeDeadModPerLevel
        {
            get
            {
                return this._flatTimeDeadModPerLevel;
            }
            set
            {
                this._flatTimeDeadModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatArmorModPerLevel
        {
            get
            {
                return this._flatArmorModPerLevel;
            }
            set
            {
                this._flatArmorModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentAttackSpeedMod
        {
            get
            {
                return this._percentAttackSpeedMod;
            }
            set
            {
                this._percentAttackSpeedMod = value;
            }
        }
        
        // 
        public double ReName_FlatDodgeModPerLevel
        {
            get
            {
                return this._flatDodgeModPerLevel;
            }
            set
            {
                this._flatDodgeModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentMagicDamageMod
        {
            get
            {
                return this._percentMagicDamageMod;
            }
            set
            {
                this._percentMagicDamageMod = value;
            }
        }
        
        // 
        public double ReName_PercentBlockMod
        {
            get
            {
                return this._percentBlockMod;
            }
            set
            {
                this._percentBlockMod = value;
            }
        }
        
        // 
        public double ReName_FlatDodgeMod
        {
            get
            {
                return this._flatDodgeMod;
            }
            set
            {
                this._flatDodgeMod = value;
            }
        }
        
        // 
        public double ReName_FlatEnergyRegenMod
        {
            get
            {
                return this._flatEnergyRegenMod;
            }
            set
            {
                this._flatEnergyRegenMod = value;
            }
        }
        
        // 
        public double ReName_FlatHPModPerLevel
        {
            get
            {
                return this._flatHPModPerLevel;
            }
            set
            {
                this._flatHPModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentAttackSpeedModPerLevel
        {
            get
            {
                return this._percentAttackSpeedModPerLevel;
            }
            set
            {
                this._percentAttackSpeedModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentSpellVampMod
        {
            get
            {
                return this._percentSpellVampMod;
            }
            set
            {
                this._percentSpellVampMod = value;
            }
        }
        
        // 
        public double ReName_FlatMPRegenMod
        {
            get
            {
                return this._flatMPRegenMod;
            }
            set
            {
                this._flatMPRegenMod = value;
            }
        }
        
        // 
        public double ReName_PercentHPPoolMod
        {
            get
            {
                return this._percentHPPoolMod;
            }
            set
            {
                this._percentHPPoolMod = value;
            }
        }
        
        // 
        public double ReName_PercentDodgeMod
        {
            get
            {
                return this._percentDodgeMod;
            }
            set
            {
                this._percentDodgeMod = value;
            }
        }
        
        // 
        public double ReName_FlatAttackSpeedMod
        {
            get
            {
                return this._flatAttackSpeedMod;
            }
            set
            {
                this._flatAttackSpeedMod = value;
            }
        }
        
        // 
        public double ReName_FlatArmorMod
        {
            get
            {
                return this._flatArmorMod;
            }
            set
            {
                this._flatArmorMod = value;
            }
        }
        
        // 
        public double ReName_FlatMagicDamageModPerLevel
        {
            get
            {
                return this._flatMagicDamageModPerLevel;
            }
            set
            {
                this._flatMagicDamageModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatHPRegenMod
        {
            get
            {
                return this._flatHPRegenMod;
            }
            set
            {
                this._flatHPRegenMod = value;
            }
        }
        
        // 
        public double ReName_PercentPhysicalDamageMod
        {
            get
            {
                return this._percentPhysicalDamageMod;
            }
            set
            {
                this._percentPhysicalDamageMod = value;
            }
        }
        
        // 
        public double ReName_FlatCritChanceModPerLevel
        {
            get
            {
                return this._flatCritChanceModPerLevel;
            }
            set
            {
                this._flatCritChanceModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatSpellBlockModPerLevel
        {
            get
            {
                return this._flatSpellBlockModPerLevel;
            }
            set
            {
                this._flatSpellBlockModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentTimeDeadMod
        {
            get
            {
                return this._percentTimeDeadMod;
            }
            set
            {
                this._percentTimeDeadMod = value;
            }
        }
        
        // 
        public double ReName_FlatBlockMod
        {
            get
            {
                return this._flatBlockMod;
            }
            set
            {
                this._flatBlockMod = value;
            }
        }
        
        // 
        public double ReName_PercentMPPoolMod
        {
            get
            {
                return this._percentMPPoolMod;
            }
            set
            {
                this._percentMPPoolMod = value;
            }
        }
        
        // 
        public double ReName_FlatMagicDamageMod
        {
            get
            {
                return this._flatMagicDamageMod;
            }
            set
            {
                this._flatMagicDamageMod = value;
            }
        }
        
        // 
        public double ReName_PercentMPRegenMod
        {
            get
            {
                return this._percentMPRegenMod;
            }
            set
            {
                this._percentMPRegenMod = value;
            }
        }
        
        // 
        public double ReName_PercentMovementSpeedModPerLevel
        {
            get
            {
                return this._percentMovementSpeedModPerLevel;
            }
            set
            {
                this._percentMovementSpeedModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentCooldownModPerLevel
        {
            get
            {
                return this._percentCooldownModPerLevel;
            }
            set
            {
                this._percentCooldownModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatMPModPerLevel
        {
            get
            {
                return this._flatMPModPerLevel;
            }
            set
            {
                this._flatMPModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatEnergyModPerLevel
        {
            get
            {
                return this._flatEnergyModPerLevel;
            }
            set
            {
                this._flatEnergyModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatPhysicalDamageMod
        {
            get
            {
                return this._flatPhysicalDamageMod;
            }
            set
            {
                this._flatPhysicalDamageMod = value;
            }
        }
        
        // 
        public double ReName_FlatHPRegenModPerLevel
        {
            get
            {
                return this._flatHPRegenModPerLevel;
            }
            set
            {
                this._flatHPRegenModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatCritDamageMod
        {
            get
            {
                return this._flatCritDamageMod;
            }
            set
            {
                this._flatCritDamageMod = value;
            }
        }
        
        // 
        public double ReName_PercentArmorMod
        {
            get
            {
                return this._percentArmorMod;
            }
            set
            {
                this._percentArmorMod = value;
            }
        }
        
        // 
        public double ReName_FlatMagicPenetrationMod
        {
            get
            {
                return this._flatMagicPenetrationMod;
            }
            set
            {
                this._flatMagicPenetrationMod = value;
            }
        }
        
        // 
        public double ReName_PercentCritChanceMod
        {
            get
            {
                return this._percentCritChanceMod;
            }
            set
            {
                this._percentCritChanceMod = value;
            }
        }
        
        // 
        public double ReName_FlatPhysicalDamageModPerLevel
        {
            get
            {
                return this._flatPhysicalDamageModPerLevel;
            }
            set
            {
                this._flatPhysicalDamageModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentArmorPenetrationMod
        {
            get
            {
                return this._percentArmorPenetrationMod;
            }
            set
            {
                this._percentArmorPenetrationMod = value;
            }
        }
        
        // 
        public double ReName_PercentEXPBonus
        {
            get
            {
                return this._percentEXPBonus;
            }
            set
            {
                this._percentEXPBonus = value;
            }
        }
        
        // 
        public double ReName_FlatMPRegenModPerLevel
        {
            get
            {
                return this._flatMPRegenModPerLevel;
            }
            set
            {
                this._flatMPRegenModPerLevel = value;
            }
        }
        
        // 
        public double ReName_PercentMagicPenetrationModPerLevel
        {
            get
            {
                return this._percentMagicPenetrationModPerLevel;
            }
            set
            {
                this._percentMagicPenetrationModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatTimeDeadMod
        {
            get
            {
                return this._flatTimeDeadMod;
            }
            set
            {
                this._flatTimeDeadMod = value;
            }
        }
        
        // 
        public double ReName_FlatMovementSpeedModPerLevel
        {
            get
            {
                return this._flatMovementSpeedModPerLevel;
            }
            set
            {
                this._flatMovementSpeedModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatGoldPer10Mod
        {
            get
            {
                return this._flatGoldPer10Mod;
            }
            set
            {
                this._flatGoldPer10Mod = value;
            }
        }
        
        // 
        public double ReName_FlatArmorPenetrationMod
        {
            get
            {
                return this._flatArmorPenetrationMod;
            }
            set
            {
                this._flatArmorPenetrationMod = value;
            }
        }
        
        // 
        public double ReName_FlatCritDamageModPerLevel
        {
            get
            {
                return this._flatCritDamageModPerLevel;
            }
            set
            {
                this._flatCritDamageModPerLevel = value;
            }
        }
        
        // 
        public double ReName_FlatHPPoolMod
        {
            get
            {
                return this._flatHPPoolMod;
            }
            set
            {
                this._flatHPPoolMod = value;
            }
        }
        
        // 
        public double ReName_FlatCritChanceMod
        {
            get
            {
                return this._flatCritChanceMod;
            }
            set
            {
                this._flatCritChanceMod = value;
            }
        }
        
        // 
        public double ReName_FlatEXPBonus
        {
            get
            {
                return this._flatEXPBonus;
            }
            set
            {
                this._flatEXPBonus = value;
            }
        }
    }
}
