//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains champion skin data.
    public class SkinDtoStatic
    {
        
        // 
        [JsonProperty("num")]
        private int _num;
        
        // 
        [JsonProperty("name")]
        private string _name;
        
        // 
        [JsonProperty("id")]
        private int _id;
        
        // 
        public int Num
        {
            get
            {
                return this._num;
            }
            set
            {
                this._num = value;
            }
        }
        
        // 
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        // 
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
    }
}
