//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Static_Data_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains champion stats data.
    public class StatsDtoStatic
    {
        
        // 
        [JsonProperty("armorperlevel")]
        private double _armorperlevel;
        
        // 
        [JsonProperty("hpperlevel")]
        private double _hpperlevel;
        
        // 
        [JsonProperty("attackdamage")]
        private double _attackdamage;
        
        // 
        [JsonProperty("mpperlevel")]
        private double _mpperlevel;
        
        // 
        [JsonProperty("attackspeedoffset")]
        private double _attackspeedoffset;
        
        // 
        [JsonProperty("armor")]
        private double _armor;
        
        // 
        [JsonProperty("hp")]
        private double _hp;
        
        // 
        [JsonProperty("hpregenperlevel")]
        private double _hpregenperlevel;
        
        // 
        [JsonProperty("spellblock")]
        private double _spellblock;
        
        // 
        [JsonProperty("attackrange")]
        private double _attackrange;
        
        // 
        [JsonProperty("movespeed")]
        private double _movespeed;
        
        // 
        [JsonProperty("attackdamageperlevel")]
        private double _attackdamageperlevel;
        
        // 
        [JsonProperty("mpregenperlevel")]
        private double _mpregenperlevel;
        
        // 
        [JsonProperty("mp")]
        private double _mp;
        
        // 
        [JsonProperty("spellblockperlevel")]
        private double _spellblockperlevel;
        
        // 
        [JsonProperty("crit")]
        private double _crit;
        
        // 
        [JsonProperty("mpregen")]
        private double _mpregen;
        
        // 
        [JsonProperty("attackspeedperlevel")]
        private double _attackspeedperlevel;
        
        // 
        [JsonProperty("hpregen")]
        private double _hpregen;
        
        // 
        [JsonProperty("critperlevel")]
        private double _critperlevel;
        
        // 
        public double Armorperlevel
        {
            get
            {
                return this._armorperlevel;
            }
            set
            {
                this._armorperlevel = value;
            }
        }
        
        // 
        public double Hpperlevel
        {
            get
            {
                return this._hpperlevel;
            }
            set
            {
                this._hpperlevel = value;
            }
        }
        
        // 
        public double Attackdamage
        {
            get
            {
                return this._attackdamage;
            }
            set
            {
                this._attackdamage = value;
            }
        }
        
        // 
        public double Mpperlevel
        {
            get
            {
                return this._mpperlevel;
            }
            set
            {
                this._mpperlevel = value;
            }
        }
        
        // 
        public double Attackspeedoffset
        {
            get
            {
                return this._attackspeedoffset;
            }
            set
            {
                this._attackspeedoffset = value;
            }
        }
        
        // 
        public double Armor
        {
            get
            {
                return this._armor;
            }
            set
            {
                this._armor = value;
            }
        }
        
        // 
        public double Hp
        {
            get
            {
                return this._hp;
            }
            set
            {
                this._hp = value;
            }
        }
        
        // 
        public double Hpregenperlevel
        {
            get
            {
                return this._hpregenperlevel;
            }
            set
            {
                this._hpregenperlevel = value;
            }
        }
        
        // 
        public double Spellblock
        {
            get
            {
                return this._spellblock;
            }
            set
            {
                this._spellblock = value;
            }
        }
        
        // 
        public double Attackrange
        {
            get
            {
                return this._attackrange;
            }
            set
            {
                this._attackrange = value;
            }
        }
        
        // 
        public double Movespeed
        {
            get
            {
                return this._movespeed;
            }
            set
            {
                this._movespeed = value;
            }
        }
        
        // 
        public double Attackdamageperlevel
        {
            get
            {
                return this._attackdamageperlevel;
            }
            set
            {
                this._attackdamageperlevel = value;
            }
        }
        
        // 
        public double Mpregenperlevel
        {
            get
            {
                return this._mpregenperlevel;
            }
            set
            {
                this._mpregenperlevel = value;
            }
        }
        
        // 
        public double Mp
        {
            get
            {
                return this._mp;
            }
            set
            {
                this._mp = value;
            }
        }
        
        // 
        public double Spellblockperlevel
        {
            get
            {
                return this._spellblockperlevel;
            }
            set
            {
                this._spellblockperlevel = value;
            }
        }
        
        // 
        public double Crit
        {
            get
            {
                return this._crit;
            }
            set
            {
                this._crit = value;
            }
        }
        
        // 
        public double Mpregen
        {
            get
            {
                return this._mpregen;
            }
            set
            {
                this._mpregen = value;
            }
        }
        
        // 
        public double Attackspeedperlevel
        {
            get
            {
                return this._attackspeedperlevel;
            }
            set
            {
                this._attackspeedperlevel = value;
            }
        }
        
        // 
        public double Hpregen
        {
            get
            {
                return this._hpregen;
            }
            set
            {
                this._hpregen = value;
            }
        }
        
        // 
        public double Critperlevel
        {
            get
            {
                return this._critperlevel;
            }
            set
            {
                this._critperlevel = value;
            }
        }
    }
}
