//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.League_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class LeaguePositionDTO
    {
        
        // 
        [JsonProperty("rank")]
        private string _rank;
        
        // 
        [JsonProperty("queueType")]
        private string _queueType;
        
        // 
        [JsonProperty("hotStreak")]
        private bool _hotStreak;


        [JsonProperty("miniSeries")]
        private MiniSeriesDTO _miniSeries;
        
        // 
        [JsonProperty("wins")]
        private int _wins;
        
        // 
        [JsonProperty("veteran")]
        private bool _veteran;
        
        // 
        [JsonProperty("losses")]
        private int _losses;
        
        // 
        [JsonProperty("playerOrTeamId")]
        private string _playerOrTeamId;
        
        // 
        [JsonProperty("leagueName")]
        private string _leagueName;
        
        // 
        [JsonProperty("playerOrTeamName")]
        private string _playerOrTeamName;
        
        // 
        [JsonProperty("inactive")]
        private bool _inactive;
        
        // 
        [JsonProperty("freshBlood")]
        private bool _freshBlood;
        
        // 
        [JsonProperty("tier")]
        private string _tier;
        
        // 
        [JsonProperty("leaguePoints")]
        private int _leaguePoints;
        
        // 
        public string Rank
        {
            get
            {
                return this._rank;
            }
            set
            {
                this._rank = value;
            }
        }
        
        // 
        public string QueueType
        {
            get
            {
                return this._queueType;
            }
            set
            {
                this._queueType = value;
            }
        }
        
        // 
        public bool HotStreak
        {
            get
            {
                return this._hotStreak;
            }
            set
            {
                this._hotStreak = value;
            }
        }
        
        // 
        public MiniSeriesDTO MiniSeries
        {
            get
            {
                return this._miniSeries;
            }
            set
            {
                this._miniSeries = value;
            }
        }
        
        // 
        public int Wins
        {
            get
            {
                return this._wins;
            }
            set
            {
                this._wins = value;
            }
        }
        
        // 
        public bool Veteran
        {
            get
            {
                return this._veteran;
            }
            set
            {
                this._veteran = value;
            }
        }
        
        // 
        public int Losses
        {
            get
            {
                return this._losses;
            }
            set
            {
                this._losses = value;
            }
        }
        
        // 
        public string PlayerOrTeamId
        {
            get
            {
                return this._playerOrTeamId;
            }
            set
            {
                this._playerOrTeamId = value;
            }
        }
        
        // 
        public string LeagueName
        {
            get
            {
                return this._leagueName;
            }
            set
            {
                this._leagueName = value;
            }
        }
        
        // 
        public string PlayerOrTeamName
        {
            get
            {
                return this._playerOrTeamName;
            }
            set
            {
                this._playerOrTeamName = value;
            }
        }
        
        // 
        public bool Inactive
        {
            get
            {
                return this._inactive;
            }
            set
            {
                this._inactive = value;
            }
        }
        
        // 
        public bool FreshBlood
        {
            get
            {
                return this._freshBlood;
            }
            set
            {
                this._freshBlood = value;
            }
        }
        
        // 
        public string Tier
        {
            get
            {
                return this._tier;
            }
            set
            {
                this._tier = value;
            }
        }
        
        // 
        public int LeaguePoints
        {
            get
            {
                return this._leaguePoints;
            }
            set
            {
                this._leaguePoints = value;
            }
        }
    }
}
