//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.League_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class MiniSeriesDTO
    {
        
        // 
        [JsonProperty("wins")]
        private int _wins;
        
        // 
        [JsonProperty("losses")]
        private int _losses;
        
        // 
        [JsonProperty("target")]
        private int _target;
        
        // 
        [JsonProperty("progress")]
        private string _progress;
        
        // 
        public int Wins
        {
            get
            {
                return this._wins;
            }
            set
            {
                this._wins = value;
            }
        }
        
        // 
        public int Losses
        {
            get
            {
                return this._losses;
            }
            set
            {
                this._losses = value;
            }
        }
        
        // 
        public int Target
        {
            get
            {
                return this._target;
            }
            set
            {
                this._target = value;
            }
        }
        
        // 
        public string Progress
        {
            get
            {
                return this._progress;
            }
            set
            {
                this._progress = value;
            }
        }
    }
}
