//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Summoner_V3
{
    using Newtonsoft.Json;
    using RiotSharp.Misc;
    using RiotSharp.Misc.Converters;
    using System;
    
    
    // - represents a summoner
    public class SummonerDTO
    {

        public Region Region { get; set; }
        
        // ID of the summoner icon associated with the summoner.
        [JsonProperty("profileIconId")]
        private int _profileIconId;
        
        // Summoner name.
        [JsonProperty("name")]
        private string _name;
        
        // Summoner level associated with the summoner.
        [JsonProperty("summonerLevel")]
        private long _summonerLevel;
        
        // Date summoner was last modified specified as epoch milliseconds. The following events will update this timestamp: profile icon change, playing the tutorial or advanced tutorial, finishing a game, summoner name change
        [JsonProperty("revisionDate")]
        [JsonConverter(typeof(DateTimeConverterFromLong))]
        private DateTime _revisionDate;
        
        // Summoner ID.
        [JsonProperty("id")]
        private long _id;
        
        // Account ID.
        [JsonProperty("accountId")]
        private long _accountId;
        
        // ID of the summoner icon associated with the summoner.
        public int ProfileIconId
        {
            get
            {
                return this._profileIconId;
            }
            set
            {
                this._profileIconId = value;
            }
        }
        
        // Summoner name.
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        // Summoner level associated with the summoner.
        public long SummonerLevel
        {
            get
            {
                return this._summonerLevel;
            }
            set
            {
                this._summonerLevel = value;
            }
        }
        
        // Date summoner was last modified specified as epoch milliseconds. The following events will update this timestamp: profile icon change, playing the tutorial or advanced tutorial, finishing a game, summoner name change
        public DateTime RevisionDate
        {
            get
            {
                return this._revisionDate;
            }
            set
            {
                this._revisionDate = value;
            }
        }
        
        // Summoner ID.
        public long Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        // Account ID.
        public long AccountId
        {
            get
            {
                return this._accountId;
            }
            set
            {
                this._accountId = value;
            }
        }
    }
}
