//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Runes_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains rune page information.
    public class RunePageDto
    {
        
        // Indicates if the page is the current page.
        [JsonProperty("current")]
        private bool _current;
        
        // Collection of rune slots associated with the rune page.
        [JsonProperty("slots")]
        private List<RuneSlotDto> _slots;
        
        // Rune page name.
        [JsonProperty("name")]
        private string _name;
        
        // Rune page ID.
        [JsonProperty("id")]
        private long _id;
        
        // Indicates if the page is the current page.
        public bool Current
        {
            get
            {
                return this._current;
            }
            set
            {
                this._current = value;
            }
        }
        
        // Collection of rune slots associated with the rune page.
        public List<RuneSlotDto> Slots
        {
            get
            {
                return this._slots;
            }
            set
            {
                this._slots = value;
            }
        }
        
        // Rune page name.
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        // Rune page ID.
        public long Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
    }
}
