//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Tournament_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class TournamentCodeDTO
    {
        
        // The game map for the tournament code game
        [JsonProperty("map")]
        private string _map;
        
        // The tournament code.
        [JsonProperty("code")]
        private string _code;
        
        // The spectator mode for the tournament code game.
        [JsonProperty("spectators")]
        private string _spectators;
        
        // The tournament code's region.
        //             (Legal values:  BR,  EUNE,  EUW,  JP,  LAN,  LAS,  NA,  OCE,  PBE,  RU,  TR)
        [JsonProperty("region")]
        private string _region;
        
        // The provider's ID.
        [JsonProperty("providerId")]
        private int _providerId;
        
        // The team size for the tournament code game.
        [JsonProperty("teamSize")]
        private int _teamSize;
        
        // 
        [JsonProperty("participants")]
        private List<long> _participants;
        
        // The pick mode for tournament code game.
        [JsonProperty("pickType")]
        private string _pickType;
        
        // The tournament's ID.
        [JsonProperty("tournamentId")]
        private int _tournamentId;
        
        // The lobby name for the tournament code game.
        [JsonProperty("lobbyName")]
        private string _lobbyName;
        
        // The password for the tournament code game.
        [JsonProperty("password")]
        private string _password;
        
        // The tournament code's ID.
        [JsonProperty("id")]
        private int _id;
        
        // The metadata for tournament code.
        [JsonProperty("metaData")]
        private string _metaData;
        
        // The game map for the tournament code game
        public string Map
        {
            get
            {
                return this._map;
            }
            set
            {
                this._map = value;
            }
        }
        
        // The tournament code.
        public string Code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        
        // The spectator mode for the tournament code game.
        public string Spectators
        {
            get
            {
                return this._spectators;
            }
            set
            {
                this._spectators = value;
            }
        }
        
        // The tournament code's region.
        //             (Legal values:  BR,  EUNE,  EUW,  JP,  LAN,  LAS,  NA,  OCE,  PBE,  RU,  TR)
        public string Region
        {
            get
            {
                return this._region;
            }
            set
            {
                this._region = value;
            }
        }
        
        // The provider's ID.
        public int ProviderId
        {
            get
            {
                return this._providerId;
            }
            set
            {
                this._providerId = value;
            }
        }
        
        // The team size for the tournament code game.
        public int TeamSize
        {
            get
            {
                return this._teamSize;
            }
            set
            {
                this._teamSize = value;
            }
        }
        
        // 
        public List<long> Participants
        {
            get
            {
                return this._participants;
            }
            set
            {
                this._participants = value;
            }
        }
        
        // The pick mode for tournament code game.
        public string PickType
        {
            get
            {
                return this._pickType;
            }
            set
            {
                this._pickType = value;
            }
        }
        
        // The tournament's ID.
        public int TournamentId
        {
            get
            {
                return this._tournamentId;
            }
            set
            {
                this._tournamentId = value;
            }
        }
        
        // The lobby name for the tournament code game.
        public string LobbyName
        {
            get
            {
                return this._lobbyName;
            }
            set
            {
                this._lobbyName = value;
            }
        }
        
        // The password for the tournament code game.
        public string Password
        {
            get
            {
                return this._password;
            }
            set
            {
                this._password = value;
            }
        }
        
        // The tournament code's ID.
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        // The metadata for tournament code.
        public string MetaData
        {
            get
            {
                return this._metaData;
            }
            set
            {
                this._metaData = value;
            }
        }
    }
}
