//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Champion_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains a collection of champion information.
    public class ChampionListDto
    {
        
        // The collection of champion information.
        [JsonProperty("champions")]
        private List<ChampionDto> _champions;
        
        // The collection of champion information.
        public List<ChampionDto> Champions
        {
            get
            {
                return this._champions;
            }
            set
            {
                this._champions = value;
            }
        }
    }
}
