//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Masteries_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // - This object contains masteries information.
    public class MasteryPagesDto
    {
        
        // Collection of mastery pages associated with the summoner.
        [JsonProperty("pages")]
        private List<MasteryPageDto> _pages;
        
        // Summoner ID.
        [JsonProperty("summonerId")]
        private long _summonerId;
        
        // Collection of mastery pages associated with the summoner.
        public List<MasteryPageDto> Pages
        {
            get
            {
                return this._pages;
            }
            set
            {
                this._pages = value;
            }
        }
        
        // Summoner ID.
        public long SummonerId
        {
            get
            {
                return this._summonerId;
            }
            set
            {
                this._summonerId = value;
            }
        }
    }
}
