//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Status_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class Message
    {
        
        // 
        [JsonProperty("severity")]
        private string _severity;
        
        // 
        [JsonProperty("author")]
        private string _author;
        
        // 
        [JsonProperty("created_at")]
        private string _created_at;
        
        // 
        [JsonProperty("translations")]
        private List<Translation> _translations;
        
        // 
        [JsonProperty("updated_at")]
        private string _updated_at;
        
        // 
        [JsonProperty("content")]
        private string _content;
        
        // 
        [JsonProperty("id")]
        private string _id;
        
        // 
        public string Severity
        {
            get
            {
                return this._severity;
            }
            set
            {
                this._severity = value;
            }
        }
        
        // 
        public string Author
        {
            get
            {
                return this._author;
            }
            set
            {
                this._author = value;
            }
        }
        
        // 
        public string Created_at
        {
            get
            {
                return this._created_at;
            }
            set
            {
                this._created_at = value;
            }
        }
        
        // 
        public List<Translation> Translations
        {
            get
            {
                return this._translations;
            }
            set
            {
                this._translations = value;
            }
        }
        
        // 
        public string Updated_at
        {
            get
            {
                return this._updated_at;
            }
            set
            {
                this._updated_at = value;
            }
        }
        
        // 
        public string Content
        {
            get
            {
                return this._content;
            }
            set
            {
                this._content = value;
            }
        }
        
        // 
        public string Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
    }
}
