//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Status_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class Service
    {
        
        // 
        [JsonProperty("status")]
        private string _status;
        
        // 
        [JsonProperty("incidents")]
        private List<Incident> _incidents;
        
        // 
        [JsonProperty("name")]
        private string _name;
        
        // 
        [JsonProperty("slug")]
        private string _slug;
        
        // 
        public string Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }
        
        // 
        public List<Incident> Incidents
        {
            get
            {
                return this._incidents;
            }
            set
            {
                this._incidents = value;
            }
        }
        
        // 
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        // 
        public string Slug
        {
            get
            {
                return this._slug;
            }
            set
            {
                this._slug = value;
            }
        }
    }
}
