//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Lol_Status_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class ShardStatus
    {
        
        // 
        [JsonProperty("name")]
        private string _name;
        
        // 
        [JsonProperty("region_tag")]
        private string _region_tag;
        
        // 
        [JsonProperty("hostname")]
        private string _hostname;
        
        // 
        [JsonProperty("services")]
        private List<Service> _services;
        
        // 
        [JsonProperty("slug")]
        private string _slug;
        
        // 
        [JsonProperty("locales")]
        private List<string> _locales;
        
        // 
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        // 
        public string Region_tag
        {
            get
            {
                return this._region_tag;
            }
            set
            {
                this._region_tag = value;
            }
        }
        
        // 
        public string Hostname
        {
            get
            {
                return this._hostname;
            }
            set
            {
                this._hostname = value;
            }
        }
        
        // 
        public List<Service> Services
        {
            get
            {
                return this._services;
            }
            set
            {
                this._services = value;
            }
        }
        
        // 
        public string Slug
        {
            get
            {
                return this._slug;
            }
            set
            {
                this._slug = value;
            }
        }
        
        // 
        public List<string> Locales
        {
            get
            {
                return this._locales;
            }
            set
            {
                this._locales = value;
            }
        }
    }
}
