//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Spectator_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class BannedChampion
    {
        
        // The turn during which the champion was banned
        [JsonProperty("pickTurn")]
        private int _pickTurn;
        
        // The ID of the banned champion
        [JsonProperty("championId")]
        private long _championId;
        
        // The ID of the team that banned the champion
        [JsonProperty("teamId")]
        private long _teamId;
        
        // The turn during which the champion was banned
        public int PickTurn
        {
            get
            {
                return this._pickTurn;
            }
            set
            {
                this._pickTurn = value;
            }
        }
        
        // The ID of the banned champion
        public long ChampionId
        {
            get
            {
                return this._championId;
            }
            set
            {
                this._championId = value;
            }
        }
        
        // The ID of the team that banned the champion
        public long TeamId
        {
            get
            {
                return this._teamId;
            }
            set
            {
                this._teamId = value;
            }
        }
    }
}
