//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Spectator_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class Mastery
    {
        
        // The ID of the mastery
        [JsonProperty("masteryId")]
        private long _masteryId;
        
        // The number of points put into this mastery by the user
        [JsonProperty("rank")]
        private int _rank;
        
        // The ID of the mastery
        public long MasteryId
        {
            get
            {
                return this._masteryId;
            }
            set
            {
                this._masteryId = value;
            }
        }
        
        // The number of points put into this mastery by the user
        public int Rank
        {
            get
            {
                return this._rank;
            }
            set
            {
                this._rank = value;
            }
        }
    }
}
