//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiotSharp.Spectator_V3
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Collections;
    using Newtonsoft.Json;
    
    
    // 
    public class Observer
    {
        
        // Key used to decrypt the spectator grid game data for playback
        [JsonProperty("encryptionKey")]
        private string _encryptionKey;
        
        // Key used to decrypt the spectator grid game data for playback
        public string EncryptionKey
        {
            get
            {
                return this._encryptionKey;
            }
            set
            {
                this._encryptionKey = value;
            }
        }
    }
}
